### ISSUE TITLE
Wrong query result with bloom filters

### ISSUE THREAD

**Issue by spetrunia** [facebook/mysql-5.6#809] opened 2018-04-09 19:19 UTC
I am using debug build of the current tree (tip cset 6f8a6f19b46023c0f08d87a8abd5225b4c3ed154)

When I run the attached test file without the `-master.opt` file, I get a result with a correct number of rows in the table t2:
```
...
insert t1
select (seq+9) div 10, (seq+4) div 5, (seq+4) div 5, seq, seq, 1000, "aaabbbccc"
  from ten_k;
insert t2 select * from t1;
select count(*) from t1;
count(*)
10000
select sin(0);
sin(0)
0
select count(*) from t2;
count(*)
10000
```

When I put the `b-master.opt` in place, I get a wrong query result:
```
...
insert t1
select (seq+9) div 10, (seq+4) div 5, (seq+4) div 5, seq, seq, 1000, "aaabbbccc"
  from ten_k;
insert t2 select * from t1;
select count(*) from t1;
count(*)
10000
select sin(0);
sin(0)
0
select count(*) from t2;
count(*)
0
```

**Comment by spetrunia** [comment] 2018-04-09 19:24
It's not possible attach arbitrary files here... The files:
b.test: https://gist.github.com/spetrunia/9630b2aad51738eadff54e96f31d2312
b-master.opt :  https://gist.github.com/spetrunia/63b400f25b525a137d69c10144a338b3

They are excerpts from MariaDB's variant of `bloomfilter.test`  (it is different from FB/MySQL variant of bloomfilter.test, the difference is faster loading of data into the tables.  "select sin(0)" is just for debugging, easy place to put a breakpoint at)

**Comment by hermanlee** [comment] 2018-04-09 20:14
Yes, this looks very strange:

```
mysql> select * from t1;
Empty set (0.00 sec)

mysql> explain select * from t1;
+----+-------------+-------+------+---------------+------+---------+------+-------+-------+
| id | select_type | table | type | possible_keys | key  | key_len | ref  | rows  | Extra |
+----+-------------+-------+------+---------------+------+---------+------+-------+-------+
|  1 | SIMPLE      | t1    | ALL  | NULL          | NULL | NULL    | NULL | 10000 | NULL  |
+----+-------------+-------+------+---------------+------+---------+------+-------+-------+
1 row in set (0.00 sec)

mysql> explain select count(*) from t1;
+----+-------------+-------+-------+---------------+------+---------+------+-------+-------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows  | Extra       |
+----+-------------+-------+-------+---------------+------+---------+------+-------+-------------+
|  1 | SIMPLE      | t1    | index | NULL          | id2  | 8       | NULL | 10000 | Using index |
+----+-------------+-------+-------+---------------+------+---------+------+-------+-------------+
1 row in set (0.00 sec)

mysql> select * from t1;
Empty set (0.00 sec)

mysql> select count(*) from t1;
+----------+
| count(*) |
+----------+
|    10000 |
+----------+
1 row in set (0.04 sec)

mysql>
```

**Comment by spetrunia** [comment] 2018-04-09 20:25
Confirm. It looks like table t2 is empty.
Added `set global rocksdb_force_flush_memtable_and_lzero_now=1;`, removed DROP TABLEs, and after the test one can see:

```
mysql-test/var/mysqld.1/data/.rocksdb$ for i in *sst ; do ../../../../../storage/rocksdb/sst_dump --file=$i --output_hex --command=scan | wc -l ; done 
10003
33
70003
11
```
10K are for table `ten_k`,  t1 has 10K * 7 indexes = 70K rows, but the 70K rows for `t2` are not there

**Comment by hermanlee** [comment] 2018-04-09 20:27
I don't think the problem is in t2. I think it's the selection of data from t1. Bloomfilter is being used in t1's select even though it should not be.

```
mysql> set rocksdb_skip_bloom_filter_on_read=0;
Query OK, 0 rows affected (0.00 sec)

mysql> select count(id5) from t1;
+------------+
| count(id5) |
+------------+
|          0 |
+------------+
1 row in set (0.01 sec)

mysql> set rocksdb_skip_bloom_filter_on_read=1;                                                                                                                  
Query OK, 0 rows affected (0.00 sec)

mysql> select count(id5) from t1;                                                                                                                                
+------------+
| count(id5) |
+------------+
|      10000 |
+------------+
1 row in set (0.02 sec)

mysql> 
```

**Comment by hermanlee** [comment] 2018-04-09 20:43
This might be degenerate case of the prefix extractor being set to 4 bytes, which is the size of the myrocks index number. The options for configuring the bloomfilter are passed verbatim to rocksdb, and assumes the administrator includes the 4 bytes of the myrocks index number.

**Comment by hermanlee** [comment] 2018-04-09 21:55
Discussed this with Sergey. The problem is a full table scan using the rnd interface assumes a forward scan. However, the column family is a reverse column family. So the scan performs a seek to index+1 so that next() would position it at the largest key of the index in the reverse column family.

However, since index+1 is used for seeking, the bloomfilter now filters on index+1. Since index+1 is the last key of a reverse column family table, we never scan the actual index of the table.

Sergey is going to look into an initial fix for this. We could change rnd_init to perform a similar operation to index_first() and use SeekForPrev() for reverse column families. This would also require using the appropriate next() or prev() calls. Alternatively, we could disable bloomfilters for rnd scans.

**Comment by spetrunia** [comment] 2018-04-09 23:13
Let's consider an index in a reverse-ordered CF. Suppose it has index_nr=100.

Possible RocksDB keys, in physical order:

```
 101 - x
"101"       //does not exist in db but would be here
 100 - c
 100 - b
 100 - a
"100"       //does not exist in db but would be here
  99 - x
```

We want ha_rocksdb->rnd_init(), ha_rocksdb->rnd_next() calls to walk forward in the physical order (because it's faster)

The way to do that is to call
```
it->Seek("101") 
```
this will get positioned on the record "100 - c" and then we will enumerate other records with it->Next() calls (that is, physically moving in the forward direction)

Calling Seek("101") while intending to scan records with indexnr=100 prevents use of prefix bloom filter.

(On the call I was talking about using RocksDB's SeekForPrev call. I was mistaken, this call doesn't help here)

**Comment by hermanlee** [comment] 2018-04-10 00:16
Yes. I was wondering how we handled the descending scans of reverse columns families and it looks like we have a problem there too. The following query also runs into problems:

`select id1 from t1 force index (primary) order by id1 desc;`

**Comment by hermanlee** [comment] 2018-04-10 00:22
I think in ha_rocksdb::can_use_bloom_filter(), we can check to see if the key definition's index matches the first four bytes of the eq_cond. If it doesn't, then bloom filter cannot be used.

**Comment by hermanlee** [comment] 2018-04-10 00:31
Sergey, can you try this patch? I think this will fix the issue.

```
--- a/storage/rocksdb/ha_rocksdb.cc
+++ b/storage/rocksdb/ha_rocksdb.cc
@@ -12533,7 +12533,7 @@ bool ha_rocksdb::can_use_bloom_filter(THD *thd, const Rdb_key_def &kd,
                                       const bool use_all_keys) {
   bool can_use = false;
 
-  if (THDVAR(thd, skip_bloom_filter_on_read)) {
+  if (THDVAR(thd, skip_bloom_filter_on_read) || !kd.covers_key(eq_cond)) {
     return can_use;
   }
```

**Comment by spetrunia** [comment] 2018-05-01 08:55
Here is another testcase that is related and causes assertion both with and without the above suggested patch:

Start the server with
```
rocksdb_override_cf_options='rev:cf10={block_based_table_factory={filter_policy=bloomfilter:10:false;whole_key_filtering=0;};prefix_extractor=capped:8};'
```

```
create table t34 (
  pk int unsigned not null primary key,
  kp1 int unsigned not null,
  kp2 int unsigned not null,
  col1 int unsigned,
  key(kp1, kp2) comment 'rev:cf10'
) engine=rocksdb;

# this is not really necessary?
insert into t34 values (1, 0xFFFF, 0xFFF, 12345);
```

The query
```
select * from t34 force index(kp1) where kp1=0xFFFFFFFF and kp2<=0xFFFFFFFF order by  kp2 desc;
ERROR 2006 (HY000): MySQL server has gone away
```

causes assertion failure:
```
mysqld: /home/psergey/dev-git/mysql-5.6-rocksdb-look800/storage/rocksdb/ha_rocksdb.cc:9601: void myrocks::ha_rocksdb::setup_iterator_bounds(const myrocks::Rdb_key_def&, const rocksdb::Slice&): Assertion `eq_cond_len >= Rdb_key_def::INDEX_NUMBER_SIZE' failed.
```

**Comment by spetrunia** [comment] 2018-05-01 12:58
... the issue reported in the last comment has actually nothing to do with the bloom filters. Will file it as a separate issue. The fix is to remove the assert.

**Closed as completed** 2018-08-16 17:33 UTC
Labels: bug, myrocks
