### ISSUE TITLE
Impossible WHERE noticed after reading const tables

### ISSUE THREAD

**Issue by tplavcic** [facebook/mysql-5.6#265] opened 2016-06-14 11:24 UTC
Not sure why this would happen but it works on InnoDB which returns data and MyRocks doesn't.
The problematic query is:
`SELECT c1 FROM t1 WHERE c1 = (SELECT MAX(c1) FROM t1);`
The problem seems to be with "char" column (and only when it is a key) because when I use int or varchar everything is fine.
When we execute just the subquery it works correctly on MyRocks and returns correct value.
Notice the "Impossible WHERE noticed after reading const tables" message in MyRocks explain output.

InnoDB:

```
mysql> DROP DATABASE test;
Query OK, 1 row affected (0.17 sec)

mysql> CREATE DATABASE test DEFAULT CHARACTER SET="utf8" DEFAULT COLLATE="utf8_bin";
Query OK, 1 row affected (0.00 sec)

mysql> USE test;
Database changed
mysql> CREATE TABLE t1 (c1 char(1) primary key);
Query OK, 0 rows affected (0.30 sec)

mysql> INSERT INTO t1  values ('a'),('b'),('c');
Query OK, 3 rows affected (0.08 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> SELECT c1 FROM t1 WHERE c1 = (SELECT MAX(c1) FROM t1);
+----+
| c1 |
+----+
| c  |
+----+
1 row in set (0.00 sec)

mysql> explain SELECT c1 FROM t1 WHERE c1 = (SELECT MAX(c1) FROM t1);
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
| id | select_type | table | type  | possible_keys | key     | key_len | ref   | rows | Extra                        |
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
|  1 | PRIMARY     | t1    | const | PRIMARY       | PRIMARY | 3       | const |    1 | Using index                  |
|  2 | SUBQUERY    | NULL  | NULL  | NULL          | NULL    | NULL    | NULL  | NULL | Select tables optimized away |
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
2 rows in set (0.00 sec)
```

MyRocks:

```
mysql> DROP DATABASE test;
Query OK, 1 row affected (0.03 sec)

mysql> CREATE DATABASE test DEFAULT CHARACTER SET="utf8" DEFAULT COLLATE="utf8_bin";
Query OK, 1 row affected (0.01 sec)

mysql> USE test;
Database changed
mysql> CREATE TABLE t1 (c1 char(1) primary key);
Query OK, 0 rows affected (0.20 sec)

mysql> INSERT INTO t1  values ('a'),('b'),('c');
Query OK, 3 rows affected (0.13 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> SELECT c1 FROM t1 WHERE c1 = (SELECT MAX(c1) FROM t1);
Empty set (0.01 sec)

mysql> explain SELECT c1 FROM t1 WHERE c1 = (SELECT MAX(c1) FROM t1);
+----+-------------+-------+------+---------------+------+---------+------+------+-----------------------------------------------------+
| id | select_type | table | type | possible_keys | key  | key_len | ref  | rows | Extra                                               |
+----+-------------+-------+------+---------------+------+---------+------+------+-----------------------------------------------------+
|  1 | PRIMARY     | NULL  | NULL | NULL          | NULL | NULL    | NULL | NULL | Impossible WHERE noticed after reading const tables |
|  2 | SUBQUERY    | NULL  | NULL | NULL          | NULL | NULL    | NULL | NULL | Select tables optimized away                        |
+----+-------------+-------+------+---------------+------+---------+------+------+-----------------------------------------------------+
2 rows in set (0.00 sec)
```

**Comment by yoshinorim** [comment] 2016-06-15 04:29
I couldn't reproduce this. Could you reproduce always? Or occasionally?

**Comment by tplavcic** [comment] 2016-06-15 08:43
It looks like I can reproduce it every time but it has to be a primary key on the column, if I don't set it as a key it works but it has different execution plan then.
Runtime options I'm using are:
--default-tmp-storage-engine=MyISAM --rocksdb --skip-innodb --default-storage-engine=RocksDB --collation-server=latin1_bin --rocksdb_max_open_files=-1 --rocksdb_base_background_compactions=1 --rocksdb_max_background_co    mpactions=8 --rocksdb_max_total_wal_size=4G --rocksdb_max_background_flushes=4 --rocksdb_block_size=16384 --rocksdb_block_cache_size=12G --rocksdb_lock_wait_timeout=2 --rocksdb_rpl_lookup_rows=0 --rocksdb_default_cf_options=wri    te_buffer_size=128m;target_file_size_base=32m;max_bytes_for_level_base=512m;level0_file_num_compaction_trigger=4;level0_slowdown_writes_trigger=10;level0_stop_writes_trigger=15;max_write_buffer_number=4;compression_per_level=kN    oCompression:kNoCompression:kNoCompression:kZlibCompression:kZlibCompression:kZlibCompression:kZlibCompression;compression_opts=-14:6:0;block_based_table_factory={cache_index_and_filter_blocks=1;filter_policy=bloomfilter:10:fal    se;whole_key_filtering=0};prefix_extractor=capped:12;level_compaction_dynamic_level_bytes=true;optimize_filters_for_hits=true

**Comment by yoshinorim** [comment] 2016-06-16 00:54
@tplavcic Could you please check if this is fixed by https://reviews.facebook.net/D59715 ?

**Comment by tplavcic** [comment] 2016-06-16 10:53
@yoshinorim 
It looks fixed to me:

```
mysql> DROP DATABASE test;
Query OK, 1 row affected (0.05 sec)

mysql> CREATE DATABASE test DEFAULT CHARACTER SET="utf8" DEFAULT COLLATE="utf8_bin";
Query OK, 1 row affected (0.00 sec)

mysql> USE test;
Database changed
mysql> CREATE TABLE t1 (c1 char(1) primary key);
Query OK, 0 rows affected (0.12 sec)

mysql> INSERT INTO t1  values ('a'),('b'),('c');
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> SELECT c1 FROM t1 WHERE c1 = (SELECT MAX(c1) FROM t1);
+----+
| c1 |
+----+
| c  |
+----+
1 row in set (0.00 sec)

mysql> explain SELECT c1 FROM t1 WHERE c1 = (SELECT MAX(c1) FROM t1);
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
| id | select_type | table | type  | possible_keys | key     | key_len | ref   | rows | Extra                        |
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
|  1 | PRIMARY     | t1    | const | PRIMARY       | PRIMARY | 3       | const |    1 | Using index                  |
|  2 | SUBQUERY    | NULL  | NULL  | NULL          | NULL    | NULL    | NULL  | NULL | Select tables optimized away |
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
2 rows in set (0.00 sec)
```

**Closed as completed** 2016-06-16 15:24 UTC
