### ISSUE TITLE
TRUNCATE TABLE is very slow for a partitioned MyRocks table

### ISSUE THREAD

**Issue by spetrunia** [facebook/mysql-5.6#676] opened 2017-08-06 21:32 UTC
TRUNCATE TABLE works instantly for regular MyRocks tables but is very slow for partitioned MyRocks table. 
This is not a ha_partition problem because, for InnoDB, TRUNCATE TABLE is instant for both regular and partitioned tables.

```
create table ten(a int);
insert into ten values (0),(1),(2),(3),(4),(5),(6),(7),(8),(9);
create table one_k(a int);
insert into one_k select A.a + B.a* 10 + C.a * 100 from ten A, ten B, ten C;
```

```
create table t1 (
  pk int not null primary key,
  col1 int not null
) engine=rocksdb;

create table t2 (
  pk int not null primary key,
  col1 int not null
) engine=innodb partition by hash(pk) partitions 2;
```

Insert 1M rows in both tables:

```
MySQL [test]> insert into t1 select A.a + 1000 *B.a, 1234567 from one_k A, one_k B; 
Query OK, 1000000 rows affected (12.13 sec)
Records: 1000000  Duplicates: 0  Warnings: 0

MySQL [test]> insert into t2 select A.a + 1000 *B.a, 1234567 from one_k A, one_k B; 
Query OK, 1000000 rows affected (16.32 sec)
Records: 1000000  Duplicates: 0  Warnings: 0
```

```
MySQL [test]> truncate table t1;
Query OK, 0 rows affected (0.01 sec)
```

```
MySQL [test]> truncate table t2;
```
This just hangs forever. I waited 400 seconds before killing it:
```
MySQL [(none)]> show processlist\G
*************************** 1. row ***************************
           Id: 1
         User: root
         Host: localhost
           db: test
      Command: Query
         Time: 393
        State: checking permissions
         Info: truncate table t2
Rows examined: 0
    Rows sent: 0
          Tid: 30206
       Srv_Id: 0
```

**Comment by spetrunia** [comment] 2017-08-06 21:33
With InnoDB, TRUNCATE is instant for both kinds of tables:

```
MySQL [test]> truncate table t1;
Query OK, 0 rows affected (0.06 sec)

MySQL [test]> truncate table t2;
Query OK, 0 rows affected (0.06 sec)
```

**Comment by alxyang** [comment] 2017-08-06 21:37
this is a duplicate of https://github.com/facebook/mysql-5.6/issues/619, but work is still needed to implement the fast drop index optimizations under the hood.

**Comment by yoshinorim** [comment] 2019-04-25 17:19
Fixed in https://github.com/facebook/mysql-5.6/commit/8cc282bc1a294237aa614eae60d057f62c625bf1

**Closed as completed by yoshinorim** 2019-04-25 17:19 UTC
Labels: enhancement, myrocks
