### ISSUE TITLE
Once out of disk and restart, recovery will seem impossible. This was a few months ago, is it fixed?

### ISSUE THREAD

**Issue by hiqsociety** [facebook/mysql-5.6#1161] opened 2021-02-26 12:39 UTC
Once out of disk and restart, recovery will seem impossible even when you have allocated more free space thereafter. This was a few months ago, is it fixed?

**Comment by yoshinorim** [comment] 2021-02-26 17:00
No, you should be able to recover if allocating free space. What error did you get on recovery?

**Comment by hiqsociety** [comment] 2021-06-03 04:04
it does not have error but the mysql is not able to be connected / unresponsive when started

**Comment by yoshinorim** [comment] 2021-06-03 04:13
If mysql is not responsive, it should be errors in MySQL err log. Please paste the details of the error. Also, try with the newest MyRocks branch and see if it reproduces.

I am closing this issue since we addressed out of space failure case before. Please feel free to reopen with err logs if you have repro.

**Closed as completed by yoshinorim** 2021-06-03 04:13 UTC
