### ISSUE TITLE
make[2]: *** No rule to make target '/usr/lib/libsnappy.a', needed by 'storage/rocksdb/ldb'.  Stop.

### ISSUE THREAD

**Issue by javacty** [facebook/mysql-5.6#354] opened 2016-10-23 01:41 UTC
Ubuntu 16
gcc 6.2.0

export WITH_SNAPPY=/usr
export WITH_BZ2=/usr
export WITH_LZ4=/usr
export WITH_ZSTD=/usr
<pre>
[ 44%] Linking CXX static library librocksdb_se.a
[ 44%] Built target rocksdb_se
[ 44%] Building CXX object storage/rocksdb/CMakeFiles/ldb.dir/**/**/rocksdb/tools/ldb.cc.o
[ 44%] Building CXX object storage/rocksdb/CMakeFiles/ldb.dir/**/**/rocksdb/tools/ldb_tool.cc.o
[ 44%] Building CXX object storage/rocksdb/CMakeFiles/ldb.dir/**/**/rocksdb/tools/ldb_cmd.cc.o
[ 44%] Building CXX object storage/rocksdb/CMakeFiles/ldb.dir/**/**/rocksdb/tools/sst_dump_tool.cc.o
make[2]: **\* No rule to make target '/usr/lib/libsnappy.a', needed by 'storage/rocksdb/ldb'.  Stop.
CMakeFiles/Makefile2:1047: recipe for target 'storage/rocksdb/CMakeFiles/ldb.dir/all' failed
make[1]: **\* [storage/rocksdb/CMakeFiles/ldb.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by mdcallag** [comment] 2016-10-23 01:54
Ubuntu 16.04 or 16.10?

On 16.04, the interesting files
$ dpkg -L libsnappy-dev
/usr/lib/x86_64-linux-gnu/libsnappy.a
/usr/include/snappy.h
/usr/lib/x86_64-linux-gnu/libsnappy.so

And from storage/rocksdb/CMakeLists.txt the suffix of the search path hardwired to $WITH_SNAPPY/lib/libsnappy.a

```
SET(rocksdb_static_libs )
IF (NOT "$ENV{WITH_SNAPPY}" STREQUAL "")
  SET(rocksdb_static_libs ${rocksdb_static_libs}
  $ENV{WITH_SNAPPY}/lib/libsnappy${PIC_EXT}.a)
  ADD_DEFINITIONS(-DSNAPPY)
ELSE()
  SET(rocksdb_static_libs ${rocksdb_static_libs} snappy)
ENDIF()
```

**Comment by mdcallag** [comment] 2016-10-23 01:55
Duplicate of https://github.com/facebook/mysql-5.6/issues/197

**Comment by mdcallag** [comment] 2016-10-23 03:34
The short term workaround is to edit storage/rocksdb/CMakeLists.txt.
The long term workaround is to use MariaDB Server or Percona Server once they include MyRocks.

**Closed as completed** 2016-11-21 21:18 UTC
Labels: bug, myrocks
