### ISSUE TITLE
`Insert on duplicate key update` updates the wrong row

### ISSUE THREAD

**Issue by royguo** [facebook/mysql-5.6#1035] opened 2019-07-22 10:57 UTC
Table: 

```
CREATE TABLE `video_extra` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `file_id` varchar(36) NOT NULL COMMENT,
  `attr_name` varchar(128) NOT NULL COMMENT,
  `attr_value` varchar(10240) NOT NULL COMMENT,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_video_extra` (`file_id`,`attr_name`),
  KEY `idx_create_time` (`created_at`),
  KEY `idx_modify_time` (`updated_at`)
) ENGINE=ROCKSDB AUTO_INCREMENT=4772064 DEFAULT CHARSET=utf8mb4
```

SQL :

```
insert into video_extra(file_id,attr_name,attr_value) values 
(?,'location','ip_address'),
(?,'poster_delay','0'),
(?,'remote_store_uri','uri'),
(?,'file_type','video') on duplicate key update attr_value=values(attr_value);

insert into video_extra(file_id,attr_name,attr_value) values 
(?,'xxx','yyy'),
(?,'location','ip_address'),
(?,'poster_delay','0'),
(?,'remote_store_uri','uri'),
(?,'file_type','video') on duplicate key update attr_value=values(attr_value);
```

If we execute the SQL concurrently, we can find a lot rows look like this:

```
-- select attr_name,attr_value from video_extra where attr_name != 'xxx' and attr_value = 'yyy' limit 10;

('location', 'yyy')
('poster_delay', 'yyy')
('remote_store_uri', 'yyy')
```

Which means the `insert on duplicate` update wrong records !

**More Information: **
I tried to dig into this issue in `sql_insert.cc`:

```
key_copy((uchar *) key, table->record[0], table->key_info + key_nr, 0);
if ((error = (table->file->ha_index_read_idx_map(table->record[1], key_nr,
                                                                 (uchar *) key, HA_WHOLE_KEY,
                                                                 HA_READ_KEY_EXACT))))
```

When the first time the insert query hits an DUP ERROR, the `ha_index_read_idx_map` will correctly find out its the second index (key_nr = 1) duplicated and then update the row without problem, but the generated auto_increment_val is not used.

Then the code will re-use the `prev_insert_id` for next insert, the problem is, next time it hits the DUP_ERROR(same thread) it looks like the generated id has already been taken by other thread and has been inserted into the table which caused DUP ERRPR on the first index (key_nr = 0).

I am not familiar with MyRocks but I assume if a thread takes an auto generated id, no other threads can take it from `m_auto_incr_val` again, right ? 

For a hot fix, can I just re-call `handler::update_auto_increment()` when there is a duplicate error on secondary index ?

```
// sql_insert.cc
if (!insert_id_consumed)
                    table->file->restore_auto_increment(prev_insert_id);

// change this to:
if (!insert_id_consumed)
                    if(key_nr > 0){
                             table->file->update_auto_increment(); 
                    }else{
                             table->file->restore_auto_increment(prev_insert_id);
                    }
                    

```

**Comment by hermanlee** [comment] 2019-07-22 16:12
Thanks for filing this issue.

In the row output, is 1234 the primary key field `id` or is it `file_id`? If it's `id`, is the row scan for the select query that returned the output running on a secondary index? If multiple keys are being written with the same primary key, they would overwrite each other within MyRocks.

It's not clear if your hotfix would work. I think we'd need to look at this more closely first. But key_nr is not 0 guaranteed to be 0 for the primary key. When MyRocks assigns an autoincrement value to a thread, it does not assign it to another thread.

**Comment by royguo** [comment] 2019-07-23 02:32
@hermanlee 

Sorry for the typo, the selected result should be :

```
-- select attr_name,attr_value from video_extra where attr_name != 'xxx' and attr_value = 'yyy' limit 10;

('location', 'yyy')
('poster_delay', 'yyy')
('remote_store_uri', 'yyy')
```

Here's a same issue in Percona MyRocks: https://jira.percona.com/browse/PS-5675


I am not quite sure what you mean by `key_nr is not 0 guaranteed to be 0 for the primary key`, the problem we met here is:

1. when an auto_increment value is not used  in thread A then it will be used for next insert.
2. A's next insert hit DUP ERR because the auto_increment value has been used by another thread B and committed to the database
3. A will try to update the row based on DUP KEY, which is the auto_increment value, turns out thread A update a row belongs to thread B.


I understand that the code intend not to let other threads get a duplicate auto_incr value, but this is what I see, since I am not an expert I cannot determine what is going wrong.


Now, I just want to confirm if there's any side effect for this change:

```
// sql_insert.cc
if (!insert_id_consumed)
                    table->file->restore_auto_increment(prev_insert_id);

// change this to:
if (!insert_id_consumed)
                    // for all non-pk DUP ERR, we update auto_incr_val for hot-fix the problem
                    if(key_nr > 0){
                             table->file->update_auto_increment(); 
                    }else{
                             table->file->restore_auto_increment(prev_insert_id);
                    }
```

**Comment by hermanlee** [comment] 2019-07-23 16:56
Thanks for linking the Percona issue. It looks to explain how the auto_increment values are getting conflicts. MyRocks reserves one autoincrement value per call and returns the count in nb_reserved_values, but the sql handler only looks at the return value in certain conditions, so it may be assuming the storage engine had allocated the desired values instead of checking the nb_reserved_values. I think auto_inc_interval_for_cur_row needs to be updated correctly.

As for your fix, what I meant is the primary key is not necessarily set key_nr = 0. I think key_nr is based on the order of the keys specified in the create table statement. I think those changes to the sql/sql_insert.cc would have side-effects on InnoDB. I suspect that you can probably not call restore_auto_increment() at all to work around the issue. You will probably see your auto increment values grow faster than expected though on InnoDB. But I have not gone through this part of the code in detail, so this is mainly by code-inspection.

**Comment by royguo** [comment] 2019-07-24 05:18
`but the sql handler only looks at the return value in certain conditions, so it may be assuming the storage engine had allocated the desired values instead of checking the nb_reserved_values.`

Did you mean that the `ha_rocksdb.cc::get_auto_increment` may not reserve a correct auto_inc_val value?

What if we check the `nb_reserved_values` in `ha_rocksdb.cc::get_auto_increment` before it returns and make it has a correct value (which is 1)? But this function looks pretty simple and I can't find any problem in it.

Ignore the whole `restore_auto_increment` looks like an acceptable work around, I will try it and see if there's anything else I can do.

And, one more thing, If I call `update_auto_increment()` every time there's a DUP ERR, what could go wrong? Thanks a lot!

Thanks for your explanation on this problem!

**Comment by hermanlee** [comment] 2019-07-24 22:15
> Did you mean that the `ha_rocksdb.cc::get_auto_increment` may not reserve a correct auto_inc_val value?
> 
> What if we check the `nb_reserved_values` in `ha_rocksdb.cc::get_auto_increment` before it returns and make it has a correct value (which is 1)? But this function looks pretty simple and I can't find any problem in it.

The sql layer makes a call to MyRocks indicating it would like to reserve nb_desired_values ids, but also provides a return value for nb_reserved_values. In other words, the sql layer wants to allocate, say, 5 ids (e.g. nb_desired_values = 5), calls to MyRocks, but MyRocks always ignores the desired number, allocates 1, and returns this in nb_reserved_values. However, the sql layer only seems to look at the nb_reserved_values count in certain conditions (i.e. table->s->next_number_keypart == 0, which seems to be saying if the auto increment field is not in a key, then look at nb_reserved_values). It otherwise seems to assume nb_reserved_values == nb_desired_values, which is not the case with MyRocks. So the conflict comes from the sql layer assuming MyRocks allocated more ids than it actually has allocated, and using ids that have not actually been allocated to it.

> And, one more thing, If I call `update_auto_increment()` every time there's a DUP ERR, what could go wrong? Thanks a lot!

I am not sure that could work. I see comments like:
```
  - In both cases, for the following rows we use those reserved values without             
    calling the handler again (we just progress in the interval, computing                 
    each new value from the previous one). Until we have exhausted them, then              
    we either take the next provided interval or call get_auto_increment()                 
    again to reserve a new interval.     
```
It seems like the code assumes the storage engine has allocated desired ids and it will keep trying those values until they're exhausted. So if the SQL layer thinks it reserved 5 ids, it will try n, n+1, n+2, n+3, n+4 before looking for a new range. It's not clear to me any of these work arounds will work.

I think the fix is either for MyRocks to support allocating nb_desired_values, or have the sql layer support nb_reserved_values correctly. The former is probably easier.

**Comment by lth** [comment] 2019-07-24 23:09
Do you know if you're running in debug or release mode? I had a closer look, but I don't have a repro to confirm this.

Looking at the Percona ticket, it looks like the issue is that we're not keeping `next_insert_id` and `auto_inc_interval_for_cur_row` in sync.

```
int handler::update_auto_increment() {
...
  /*
    next_insert_id is a "cursor" into the reserved interval, it may go greater
    than the interval, but not smaller.
  */
  DBUG_ASSERT(next_insert_id >= auto_inc_interval_for_cur_row.minimum());
...
  if ((nr = next_insert_id) >= auto_inc_interval_for_cur_row.maximum()) {
... // get a new autoinc value
  }
...
```

The comment seems to suggest a direct link between the two member variables. In `sql_insert.cc`, there is logic that checks if the current row ended up not consuming the generated autoincrement value because of a failed insert, then save it the value for the next successful insert.

The sequence of events as follows (summarizing/clarifying the example in Percona's ticket):

1. row 1 inserts successfully, gets assigned autoinc value 99, and next_insert_id is 100, and `auto_inc_interval_for_cur_row` contains [99,100],
2. Other transactions take autoinc values 100 - 108.
3. row 2 attempts to insert, gets assigned autoinc value 109, next_insert_id = 110 and `auto_inc_interval_for_cur_row` contains [109,110]. However it fails. prev_insert_id is 100, and we restore next_insert_id = 100 (but interval is still [109,110])
4. row 3 attempts to insert, calls `update_auto_increment` to fetch auto increment value, but because `next_insert_id = 100 < 110 = auto_inc_interval_for_cur_row.maximum()`, we don't fetch a new one and end up using 100 which could be an already assigned id.

If this theory is correct, then I suspect the assertion should have fired if you ran this under a debug build?

As for the fix, I guess you could always call `update_auto_increment()` and remove the id reuse logic, although you would consume more autoinc ids than usual.

If we wanted to keep the reuse logic, we should restore `next_insert_id` to index into first value of the current range. I think if we just changed the call to `restore_auto_increment(0)`, then we would always restore with `insert_id_for_cur_row`, which is the last generated autoinc value we attempted to insert with.

**Comment by royguo** [comment] 2019-07-25 07:16
@lth, I think your theory is correct and I tried with debug mode, that assertion was fired.

So I made this change:

```
handler.h::restore_auto_increment(uulong prev_insert_id){


+    if(next_insert_id < auto_inc_interval_for_cur_row.minimum()) {
+        update_auto_increment();
+        return;
+    }


    next_insert_id= (prev_insert_id > 0) ? prev_insert_id :
      insert_id_for_cur_row;
  }
```

But it doesn't work.

**Comment by lth** [comment] 2019-07-26 01:30
Your added call to `update_auto_increment` isn't doing anything. Recall that we have this code:
```
  if ((nr= next_insert_id) >= auto_inc_interval_for_cur_row.maximum())
  {
     // allocate new id
  }
```

What I meant is that `restore_auto_increment` should just always use `insert_id_for_cur_row` for that callsite, and change the call from `restore_auto_increment(prev_insert_id)` to  `restore_auto_increment(0)` means that we always use `insert_id_for_cur_row`. I haven't checked if it's safe for the other call sites though.

**Closed as completed** 2019-10-24 15:14 UTC
