### ISSUE TITLE
rocksdb group commit 

### ISSUE THREAD

**Issue by chuckcai** [facebook/mysql-5.6#481] opened 2016-12-20 08:51 UTC
There is a bug when group commit with multiple transactions mixed commit phase  and prepare phase , and allow_concurrent_memtable_write enabled, so those trxs in group can write MemTable concurrenctly. 
Transaction group will fetch versions_.last_sequence as start sequence of current batch, and it allocates SEQUENCE segment for each trx in batch by add total count of group trxs.(not count in if ShouldWriteToMemtable is false: e.g. in commit phase trx).
 
uint64_t total_byte_size = 0; 
    for (auto writer : write_group) {
      if (writer->CheckCallback(this)) {
        if (writer->ShouldWriteToMemtable()) {
          total_count += WriteBatchInternal::Count(writer->batch);
          parallel = parallel && !writer->batch->HasMerge();
        }    

        if (writer->ShouldWriteToWAL()) {
          total_byte_size = WriteBatchInternal::AppendedByteSize(
              total_byte_size, WriteBatchInternal::ByteSize(writer->batch));
        }    
      }    
    } 
Unfortunately, In write memtable phase,  write group assigns SEQUENCE NO for each trx (Writer Batch)  ignored  ShouldWriteToMemtable flag:
 
code in LaunchParallelFollowers :
  while (w != pg->last_writer) {
    // Writers that won't write don't get sequence allotment
    if (!w->CallbackFailed()) {
      sequence += WriteBatchInternal::Count(w->batch); **# // BUG HERE: not check w->** ShouldWriteToMemtable, sequence out of bound.
    }      
    w = w->link_newer;

    w->sequence = sequence; 
    w->parallel_group = pg;
    SetState(w, STATE_PARALLEL_FOLLOWER);
  }

For example, suppose last_sequence is 100, then current_sequence is 101, rocksdb group include two transaction, trx1 and trx2, trx1 is leader, trx2 is follower.
trx1: prepare phase, batch count is 3
put(key1,v1);
put(key2,v2);
put(key3,v3);
trx2: commit phase, batch count is 2
put(keyA,v1);
put(keyB,v2);

trx1 is leader, so trx2 start sequence is 101+3=104, but last_sequence = 100+2=102。In memtable, keyA sequence is 104, and keyB sequence is 105, both is bigger than last_sequence. Then followed transactions use newest sequence 102, they can't see trx2's commit.

**Comment by mdcallag** [comment] 2016-12-20 18:10
https://github.com/facebook/mysql-5.6/issues/482 might be a duplicate of this

**Comment by yoshinorim** [comment] 2017-01-26 14:47
This is fixed in RocksDB (https://github.com/facebook/rocksdb/pull/1730/commits/479ad152934402dfbe2d35cba549ccfcd8ca6de4). The commit has not been included yet in the RocksDB revision where MyRocks is referencing (stable revision). To test the fix with concurrent memtable, you can just apply the one line diff.

**Closed as completed** 2017-02-23 17:09 UTC
Labels: bug, myrocks, high-pri
