### ISSUE TITLE
'corrupt ' table with prefix blob primary + unique key

### ISSUE THREAD

**Issue by sbester** [facebook/mysql-5.6#491] opened 2017-01-01 17:21 UTC
**Problem:
----------**
Version: '5.6.27-log'  socket: '/tmp/mysql.sock'  port: 3306  Source distribution
```
2016-12-31 22:48:06 16633 [Note] CHECKTABLE t: Checking table t
2016-12-31 22:48:06 16633 [Note] CHECKTABLE t:   Checking index a
2016-12-31 22:48:06 16633 [ERROR] CHECKTABLE t:   .. row 0: failed to fetch row by rowid

mysql> check table t extended;
+--------+-------+----------+----------+
| Table  | Op    | Msg_type | Msg_text |
+--------+-------+----------+----------+
| test.t | check | error    | Corrupt  |
+--------+-------+----------+----------+
```

```
mysql> show status like '%hash%';
+------------------+------------------------------------------+
| Variable_name    | Value                                    |
+------------------+------------------------------------------+
| git_hash         | f6ed777697db4ad7aee1e98c53243dced2b5891c |
| rocksdb_git_hash | 335981d47371cef0c48ebb58af53f2c8b8d8bd35 |
+------------------+------------------------------------------+
```

**How To Repeat;
----------------**
```
set sql_mode="";
drop table if exists t;
create table t (
  a blob,
  primary key(a(2)),
  unique (a(1))
) engine=rocksdb;
insert into t values('a');
check table t extended;
```

**Comment by yoshinorim** [comment] 2017-01-03 17:25
Thanks! Verified as described.

**Comment by lth** [comment] 2017-01-03 22:50
The fix for this bug will require a format change. The problem is that for unique keys, we don't store the row id in our secondary keys, which means we can't do a PK lookup from a secondary key. The fix is just to add it in.

The fact that the PK is prefixed is irrelevant. The bug is in prefixed unique keys.

**Closed as completed** 2017-01-04 22:56 UTC
Labels: bug, myrocks, high-pri
