### ISSUE TITLE
SELECT query using JSON_VALID fails

### ISSUE THREAD

**Issue by RoelVdP** [facebook/mysql-5.6#95] opened 2015-11-07 01:00 UTC
FB-mysql-5.6.24-linux-x86_64-dbg/bin/mysqld
mysql> SELECT JSON_VALID(REPEAT('{"a":',100000));
ERROR 2013 (HY000): Lost connection to MySQL server during query

mysql-5.7.9-linux-glibc2.5-x86_64/bin/mysqld-debug
mysql> SELECT JSON_VALID(REPEAT('{"a":',100000));
ERROR 3157 (22032): The JSON document exceeds the maximum depth.

mysql-5.6.23-linux-x86_64/bin/mysqld
mysql> SELECT JSON_VALID(REPEAT('{"a":',100000));
ERROR 1305 (42000): FUNCTION test.JSON_VALID does not exist

**Comment by RoelVdP** [comment] 2015-11-07 01:01
It could be that the ported feature requires a patch available in a later 5.7 release.

**Comment by tianx** [comment] 2015-11-09 22:36
Thanks Roel for reporting this. This appears to be a bug in our (DocStore) version of JSON_VALID function. MySQL doesn't have JSON support in 5.6.

**Comment by tianx** [comment] 2015-11-10 19:49
This is a problem that we don't fail gracefully when JSON contains objects/arrays with too many nesting levels/depths. The cause of the crash is overflow of stack space because we need to backtrack nested objects for size information of the objects. As comparison, MySQL 5.7 has a hard limit of maximum 100 depths for JSON objects (due to the same reason).

I will send out a fix soon.

**Comment by tianx** [comment] 2015-11-12 18:23
Fixed in https://github.com/facebook/mysql-5.6/commit/7624eef176f37f1eb5d3962a70775d1f72f37d0f. Thanks again @RoelVdP for reporting it.

**Closed as completed by tianx** 2015-11-12 18:23 UTC
