### ISSUE TITLE
crash when setting gap_lock_exceptions to rubbish

### ISSUE THREAD

**Issue by sbester** [facebook/mysql-5.6#494] opened 2017-01-02 05:20 UTC
**Problem Description:
--------------------**

```
[Note] MySQL git hash: f6ed777697db4ad7aee1e98c53243dced2b5891c - %cI
[Note] RocksDB git hash: 335981d47371cef0c48ebb58af53f2c8b8d8bd35 - %cI
[Note] mysqld: ready for connections.
Version: '5.6.27-debug-log'  Source distribution

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7f2f700 (LWP 5017)]
in std::__detail::_StateSeq::_StateSeq 
375         : _M_nfa(__rhs._M_nfa), _M_start(__rhs._M_start),
(gdb) bt
#0  in std::__detail::_StateSeq::_StateSeq
#1  in std::__detail::_Compiler
#2  in std::__detail::_Compiler
#3  in std::__detail::__compile
#4  in std::basic_regex
#5  in Regex_list_handler::set_patterns  at ./sql/handler.cc:8224
#6  in set_regex_list_handler at ./sql/sys_vars.cc:1661
#7  in set_gap_lock_exception_list at ./sql/sys_vars.cc:1671
#8  in sys_var::update at ./sql/set_var.cc:194
#9  in set_var::update at ./sql/set_var.cc:670
#10 in sql_set_variables at ./sql/set_var.cc:573
#11 in mysql_execute_command at ./sql/sql_parse.cc:4554
#12 in mysql_parse at ./sql/sql_parse.cc:7475
#13 in dispatch_command at ./sql/sql_parse.cc:1680
#14 in do_command at ./sql/sql_parse.cc:1135
#15 in do_handle_one_connection at ./sql/sql_connect.cc:1152
#16 in handle_one_connection at ./sql/sql_connect.cc:973
#17 in start_thread at pthread_create.c:308
#18 in clone 
(gdb)
```

**How to repeat:
--------------**
```
set global gap_lock_exceptions =',$ ';
set global gap_lock_exceptions ='|*%';
set global gap_lock_exceptions =@e;
set global gap_lock_exceptions =',';
set global gap_lock_exceptions =0x7cc04e505229;
set global gap_lock_exceptions =',c';
```

**Comment by sbester** [comment] 2017-01-02 05:23
set global legacy_user_name_pattern ='|';

**Comment by jkedgar** [comment] 2017-02-25 05:29
Are you using GCC 4.8?  If so, this is a known problem.  GCC 4.8 included all the API for std::regex but did not include a full implementation, so simple things work but more complicated things like this cause failures.  Here's the bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53631.  This was resolved in GCC 4.9.

When I tried all of these values in a build done on GCC 4.9 they all succeeded fine with no crashes

We have dropped support for GCC 4.8 recently because of issues like this.

I'm going to close the issue.  If I am incorrect and you caused these on a build with GCC 4.9 or later, reopen the issue.

**Closed as completed by jkedgar** 2017-02-25 05:29 UTC

**Comment by sbester** [comment] 2017-02-25 05:32
Hi,   yes I used gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11) .
I will upgrade gcc.

Thanks!

**Comment by laurynas-biveinis** [comment] 2017-02-27 03:19
https://www.facebook.com/groups/rocksdb.dev/permalink/1176824982416014/ suggests that dropping GCC 4.8 support has not happened yet - @jkedgar could you please clarify?

**Comment by jkedgar** [comment] 2017-02-27 17:19
I have confirmed that MyRocks has dropped support for GCC 4.8.  The post you cite is for RocksDB (the underlying key/value storage solution the MyRocks uses) and MyRocks can drop support for GCC 4.8 even if RocksDB still supports it.

Unfortunately I don't see anywhere where we announced that MyRocks would be dropping GCC 4.8.  I'll try to follow up on that and see if we can make that public in a better way.

**Comment by george-lorch** [comment] 2017-02-27 17:30
This _might_ eventually cause us some heartache with MyRocks and limit our ability to build and distribute it across all of our proposed supported platforms for Percona Server. We were already planning to limit it in the same way we limit TokuDB. Only 64 bit, 'modern-ish' platforms. Currently we have no platform build that mandates 4.9, only 4.8.

std::regex will not be a problem as we are removing that dependency and using my_regex in order to avoid the 4.8 issues and to remain consistent with the regex semantics already provided by the server.

**Comment by jkedgar** [comment] 2017-02-27 17:37
I don't think we are relying on any 4.9 feature yet (with the exception of this regex stuff).  The main issue is that we are finding it difficult to maintain building/testing with 4.8 internally.

I would be happy to import a Pull Request that switches from std::regex to my_regex - assuming we don't lose some important functionality.

**Comment by george-lorch** [comment] 2017-02-27 21:55
I was considering sending up my regex work, but you may not like the direction I went. There are a few key differences.
1) I eliminated the idea of a delimited list, it is just a regex. Anyone composing a regex should be just as able to add an '|' in place of a ',' and eliminates the possibility of the list handling code replacing valid regex {"abc", "def"} with {"abc" | "def"}. Making it a list seems unnecessary.
2) The my_regex is 'traditional' regex and has some different semantics than std::regex (honestly, I wish the my_regex was updated to pcre). my_regex used for SQL regex is documented here [https://dev.mysql.com/doc/refman/5.7/en/regexp.html](https://dev.mysql.com/doc/refman/5.7/en/regexp.html). From an end user perspective, it makes sense for the server to use the same regex semantics in all places.

The work also brought up the issue of charsets and case sensitivity since my_regex is charset and case aware. Internally, table names use table_alias_charset. System variables on the other hand are probably using a different charset which I have not yet figured out. So there are likely some problems with the Facebook implementation dealing with both charsets and identifier case sensitivity (https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html). These will be addressed in my work before it lands in Percona Server.

When I have my Percona Server implementation done, I will do a quick port to Facebook MySQL and send it up for you to take in or discard as you see fit.
