### ISSUE TITLE
utf8mb4 Support - converting utf8_bin column to utf8mb4 results in corrupt database

### ISSUE THREAD

**Issue by inkrement** [facebook/mysql-5.6#667] opened 2017-07-26 05:08 UTC
Regarding the documentation only utf8_bin, latin1_bin and binary are supported yet (https://github.com/facebook/mysql-5.6/wiki/Getting-Started-with-MyRocks). AFAIK utf8_bin only supports a subset of all Unicode characters, but I would need to store also Unicode emoticons. Is an utf8mb4 support planned, is there a workaround or is already a prototype available?

**Comment by lth** [comment] 2017-07-26 17:35
We support utf8mb4 columns if they aren't in any keys. If they are in some keys though you can turn rocksdb_strict_collation_check off with the caveat that index-only scans would not work if you had utf8mb4 columns in your secondary key, and that data size may increase if you had utf8mb4 columns in your primary key.

**Comment by inkrement** [comment] 2017-07-26 18:42
good to know! I tried to convert a table from utf8_bin to utf8mb4 multiple times and it always crashed and let a corrupt database left. But creating a new table and inserting seems to work fine.

**Comment by inkrement** [comment] 2017-07-27 11:36
I tried to convert it a second time. For smaller tables it works fine, but for a medium sized (~ 5mio rows) it processes for some minutes, then mysqld crashes and it results in a corrupt database:

```
2017-07-27 13:31:41 139856843413696 [Note] RocksDB: 2 column families found
2017-07-27 13:31:41 139856843413696 [Note] RocksDB: Column Families at start:
2017-07-27 13:31:41 139856843413696 [Note]   cf=default
2017-07-27 13:31:41 139856843413696 [Note]     write_buffer_size=134217728
2017-07-27 13:31:41 139856843413696 [Note]     target_file_size_base=33554432
2017-07-27 13:31:41 139856843413696 [Note]   cf=__system__
2017-07-27 13:31:41 139856843413696 [Note]     write_buffer_size=134217728
2017-07-27 13:31:41 139856843413696 [Note]     target_file_size_base=33554432
2017-07-27 13:31:41 139856843413696 [Warning] RocksDB: Schema mismatch - Table youtube.#sql-171_438c is registered in RocksDB but does not have a .frm file
2017-07-27 13:31:41 139856843413696 [ERROR] RocksDB: Problems validating data dictionary against .frm files, exiting
2017-07-27 13:31:41 139856843413696 [ERROR] RocksDB: Failed to initialize DDL manager.
2017-07-27 13:31:41 139856843413696 [ERROR] Plugin 'ROCKSDB' init function returned error.
2017-07-27 13:31:41 139856843413696 [ERROR] Plugin 'ROCKSDB' registration as a STORAGE ENGINE failed.
```

**Comment by yoshinorim** [comment] 2017-07-27 18:14
Looks like mysqld crashed during creating MyRocks internal temporary table, lost frm and failed to restart due to strict MyRocks checking between internal data dictionary and frm file.

Did you set "default-tmp-storage-engine=MyISAM" in my.cnf? We haven't tested MyRocks temporary tables enough. Here are recommended my.cnf settings in MyRocks -- https://github.com/facebook/mysql-5.6/wiki/my.cnf-tuning

You can skip the error by setting "rocksdb_validate_tables=0" in my.cnf

**Comment by yoshinorim** [comment] 2017-07-27 19:10
Never mind the above comment about temporary table. This issue could be reproduced by injecting crash after committing into MyRocks internal data dictionary during ALTER TABLE.

**Comment by yoshinorim** [comment] 2017-07-27 19:16
I'm closing this issue and filed a separated issue to track this (https://github.com/facebook/mysql-5.6/issues/669), since it's not UTF8 specific.

**Closed as completed by yoshinorim** 2017-07-27 19:16 UTC

**Comment by inkrement** [comment] 2017-07-28 02:49
@yoshinorim Thanks! So this is not just related to rocksdb and I have also to report it to the mariadb guys to find out why mysqld crashed, right?

**Comment by yoshinorim** [comment] 2017-07-28 19:20
@inkrement If you have a core file or stack trace on crash, you can paste the stack trace here.

**Comment by mickvav** [comment] 2017-08-04 14:10
Well, If I have this issue and rocksdb_validate_tables=0, what should I do in CLI to be able to remove this setting later? Something like "drop table '#sql....'" would be enough?
And somewhat theoretical question - why do you exclude those temporary files from file listing at all?
