### ISSUE TITLE
bulk_load test fails with "Invalid argument: Keys must be added in order" error

### ISSUE THREAD

**Issue by spetrunia** [facebook/mysql-5.6#569] opened 2017-03-14 15:51 UTC
I am compiling current tree on Ubuntu 16.04.1 LTS with https://github.com/facebook/mysql-5.6/wiki/Build-Steps .

bulk_load reliably fails like this:
```
rocksdb.bulk_load                        w1 [ fail ]
        Test ended at 2017-03-13 21:23:05

CURRENT_TEST: rocksdb.bulk_load
mysqltest: At line 68: query 'LOAD DATA INFILE '$file' INTO TABLE t1' failed: 1105: [./.rocksdb/test.t1_PRIMARY_0_1.bulk_load.tmp] bulk load error: Invalid argument: Keys must be added in order

The result from queries just before the failure was:
DROP TABLE IF EXISTS t1, t2, t3;
CREATE TABLE t1(pk CHAR(5) PRIMARY KEY, a char(30), b char(30), key(a)) COLLATE 'latin1_bin';
CREATE TABLE t2(pk CHAR(5) PRIMARY KEY, a char(30), b char(30), key(a)) COLLATE 'latin1_bin';
CREATE TABLE t3(pk CHAR(5) PRIMARY KEY, a char(30), b char(30), key(a)) COLLATE 'latin1_bin'
  PARTITION BY KEY() PARTITIONS 4;
set session transaction isolation level repeatable read;
select * from information_schema.rocksdb_dbstats where stat_type='DB_NUM_SNAPSHOTS';
STAT_TYPE	VALUE
DB_NUM_SNAPSHOTS	0
start transaction with consistent snapshot;
select * from information_schema.rocksdb_dbstats where stat_type='DB_NUM_SNAPSHOTS';
STAT_TYPE	VALUE
DB_NUM_SNAPSHOTS	1
set rocksdb_bulk_load=1;
set rocksdb_bulk_load_size=100000;
LOAD DATA INFILE <input_file> INTO TABLE t1;

 - saving '/home/ubuntu/mysql-5.6/mysql-test/var/1/log/rocksdb.bulk_load/' to '/home/ubuntu/mysql-5.6/mysql-test/var/log/rocksdb.bulk_load/'
 - found 'core' (0/5)

Trying 'dbx' to get a backtrace

Trying 'gdb' to get a backtrace
Core generated by '/home/ubuntu/mysql-5.6/sql/mysqld'
Output from gdb follows. The first stack trace is from the failing thread.
The following stack traces are from all threads (so the failing one is
duplicated).
--------------------------
BFD: Warning: /home/ubuntu/mysql-5.6/mysql-test/var/log/rocksdb.bulk_load/mysqld.1/data/core is truncated: expected core file size >= 668577792, found: 279044096.

```

**Comment by jkedgar** [comment] 2017-03-14 17:17
Sergei, I am unable to reproduce this using our build system (which is not exactly the same as what you are doing).  Can you try something for me?  In mysql-test/suite/rocksdb/t/bulk_load.test can you change the $max variable from 5000000 to 20 and see if the problem still occurs?  Also, can you try removing the secondary key from column 'a' in table 't1' and see if that makes any difference?

**Comment by spetrunia** [comment] 2017-03-14 20:40
> can you change the $max variable from 5000000 to 20 and see if the problem still occurs?

Changed, updated .result file. The problem still occurs.

While doing this, I've discovered that the problem does not happen every time when I run the test on its own. If I run `rocksdb.bulk_load --parallel=4 --repeat=10` the error occurs on the second or third test.

**Comment by spetrunia** [comment] 2017-03-14 20:42
> Also, can you try removing the secondary key from column 'a' in table 't1' and see if that makes any difference?

Done, together with $max=20 change.  The problem still occurs.

**Comment by spetrunia** [comment] 2017-03-14 20:49
Further info on how to reproduce provided via email

**Comment by jkedgar** [comment] 2017-03-14 22:59
The fact that it only fails when the test is repeated is the clue.  I found a bug last week that is the culprit.  The test 1) opens the text file (into which it generates the rows to insert) in append mode and 2) fails to delete this file at the end of the test.  This means that the second time through the test you get double the number of rows and although each half is ordered the file as a whole is now incorrectly ordered.

I've got a fix out for review right now.  Until it lands you can add "--remove_file $file" at the end of mysql-test/suite/rocksdb/t/bulk_load.test to get around the problem.

**Comment by george-lorch** [comment] 2017-03-14 23:11
While we're not yet there with MyRocks, we run our mtr on occasion with --repeat=2 specifically to find test cleanup/environmental problems.

**Comment by jkedgar** [comment] 2017-03-20 16:25
This fix has landed.  Closing.

**Closed as completed by jkedgar** 2017-03-20 16:25 UTC
Labels: myrocks
