### ISSUE TITLE
Support mem comparable keys for any _bin collations

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#288] opened 2016-07-29 22:52 UTC
Currently mem comparable keys support is limited to latin1_bin, utf8_bin, and binary collations. Let's extend to other _bin collations.

**Comment by spetrunia** [comment] 2016-08-10 20:50
Mem-comparable keys are there :-). I take this task is about being able to unpack the data back from the mem-comparable form?

ucs2_bin uses my_ucs2_uni(), utf8mb4_bin uses my_mb_wc_utf8mb4(), which is more complex but they all look (and should be) reversible...

Adding index-only support will cause changes to the on-disk data format:
1. unpack_info will need to store n_trimmed_space_chars (_bin collations have space-PAD attribute)
2. the original column won't be stored in PK's key->value pair.

**Comment by lth** [comment] 2017-06-07 00:31
Duplicate of https://github.com/facebook/mysql-5.6/issues/28

**Closed as completed by lth** 2017-06-07 00:31 UTC
Labels: enhancement, myrocks, low-pri
