### ISSUE TITLE
MyRocks chooses full index scan even if range scan is more efficient

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#212] opened 2016-03-22 04:44 UTC
How to repeat:

```
create table t1 (id1 bigint, id2 bigint, c1 bigint, c2 bigint, c3 bigint, c4 bigint, c5 bigint, c6 bigint, c7 bigint, primary key (id1, id2), index i(c1, c2));

load data local infile '/data/mysql/10m.dat' into table t1 fields terminated by ',';
```

10m.dat can be created as follows. You can reduce the number of lines, depending on your machine spec.

```
#!/usr/bin/perl

for (my $i = 1; $i <= 10000000; $i++) {
  print "$i,0,$i,0,0,0,0,0,0\n";
}
```

Then run the following selects with explain.

```
mysql> explain select c1 from t1 where c1 > 10 limit 10;
+----+-------------+-------+-------+---------------+------+---------+------+----------+--------------------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows     | Extra                    |
+----+-------------+-------+-------+---------------+------+---------+------+----------+--------------------------+
|  1 | SIMPLE      | t1    | index | i             | i    | 18      | NULL | 10000000 | Using where; Using index |
+----+-------------+-------+-------+---------------+------+---------+------+----------+--------------------------+
1 row in set (0.00 sec)

mysql> explain select c1 from t1 where c1 > 100000 limit 10;
+----+-------------+-------+-------+---------------+------+---------+------+----------+--------------------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows     | Extra                    |
+----+-------------+-------+-------+---------------+------+---------+------+----------+--------------------------+
|  1 | SIMPLE      | t1    | index | i             | i    | 18      | NULL | 10000000 | Using where; Using index |
+----+-------------+-------+-------+---------------+------+---------+------+----------+--------------------------+
1 row in set (0.00 sec)

mysql> select c1 from t1 where c1 > 100000 limit 10;
+--------+
| c1     |
+--------+
| 100001 |
| 100002 |
| 100003 |
| 100004 |
| 100005 |
| 100006 |
| 100007 |
| 100008 |
| 100009 |
| 100010 |
+--------+
10 rows in set (0.06 sec)


mysql> explain select c1 from t1 where c1 > 1000000 limit 10;
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows    | Extra                    |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
|  1 | SIMPLE      | t1    | range | i             | i    | 9       | NULL | 9165276 | Using where; Using index |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
1 row in set (0.00 sec)

mysql> select c1 from t1 where c1 > 1000000 limit 10;
+---------+
| c1      |
+---------+
| 1000001 |
| 1000002 |
| 1000003 |
| 1000004 |
| 1000005 |
| 1000006 |
| 1000007 |
| 1000008 |
| 1000009 |
| 1000010 |
+---------+
10 rows in set (0.00 sec)
```

If c1 scan range was wide enough (99% in this case), MyRocks decided to do full index scan, even though in this case range scan was much more efficient.

InnoDB always did range scan properly.

```
mysql> explain select c1 from t1 where c1 > 0 limit 10;
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows    | Extra                    |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
|  1 | SIMPLE      | t1    | range | i             | i    | 9       | NULL | 4845056 | Using where; Using index |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
1 row in set (0.00 sec)

mysql> explain select c1 from t1 where c1 > 1000 limit 10;
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows    | Extra                    |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
|  1 | SIMPLE      | t1    | range | i             | i    | 9       | NULL | 4845056 | Using where; Using index |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
1 row in set (0.00 sec)

mysql> explain select c1 from t1 where c1 > 100000 limit 10;
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows    | Extra                    |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
|  1 | SIMPLE      | t1    | range | i             | i    | 9       | NULL | 4845056 | Using where; Using index |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
1 row in set (0.00 sec)

mysql> select c1 from t1 where c1 > 100000 limit 10;
+--------+
| c1     |
+--------+
| 100001 |
| 100002 |
| 100003 |
| 100004 |
| 100005 |
| 100006 |
| 100007 |
| 100008 |
| 100009 |
| 100010 |
+--------+
10 rows in set (0.00 sec)
```

**Comment by spetrunia** [comment] 2016-03-22 10:40
My first suspicion was that the cause is LIMIT optimization.
However, optimizer trace doesn't show anything about LIMIT, and one can observe the difference without the LIMIT clause, too:

InnoDB:

```
MySQL [issue212]> explain select c1 from t1 where c1 > 100000;
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows    | Extra                    |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
|  1 | SIMPLE      | t1    | range | i             | i    | 9       | NULL | 4850490 | Using where; Using index |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
```

note that rows=4.8M which is an almost 2x underestimation (the real number is 9.9M)

MyRocks:

```
MySQL [issue212]> explain select c1 from t1 where c1 > 100000;
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows    | Extra                    |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
|  1 | SIMPLE      | t1    | index | i             | i    | 18      | NULL | 9990000 | Using where; Using index |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
```

**Comment by spetrunia** [comment] 2016-03-22 10:54
Comparing optimizer_trace:

```
--- trace-innodb3.txt
+++ trace-myrocks3.txt
@@ -69,8 +69,8 @@
                 "table": "`t1`",
                 "range_analysis": {
                   "table_scan": {
-                    "rows": 9700981,
-                    "cost": 2e6
+                    "rows": 9990000,
+                    "cost": 2.5e6
                   },
                   "potential_range_indices": [
                     {
```

OK so far 

```
@@ -91,8 +91,9 @@
                   "best_covering_index_scan": {
                     "index": "i",
-                    "cost": 1.98e6,
-                    "chosen": true
+                    "cost": 1.2e7,
+                    "chosen": false,
+                    "cause": "cost"
                   },
```

Weird, why is full index scan so much more expensive in MyRocks? 

```
@@ -111,28 +112,16 @@
                  "analyzing_range_alternatives": {
                    "range_scan_alternatives": [
                      {
                        "index": "i",
                        "ranges": [
                          "100000 < c1"
                        ],
                        "index_dives_for_eq_ranges": true,
                         "rowid_ordered": false,
                         "using_mrr": false,
                         "index_only": true,
-                        "rows": 4850490,
-                        "cost": 990226,
-                        "chosen": true
+                        "rows": 10035279,
+                        "cost": 1.2e7,
+                        "chosen": false,
+                        "cause": "cost"
                       }
                     ],
```

Here, 
- InnoDB reports 4.8M rows in the range.
- MyRocks reports 10.0M  (btw the number is bigger than total #rows in the table it reported)

The real number is 9.9M, so MyRocks is closer to truth.
However, the result is that range access is chosen for InnoDB but not for MyRocks.

**Comment by spetrunia** [comment] 2016-03-22 11:02
If I put a breakpoint into ha_innobase::records_in_range and force it to return the exact number of rows in the range (9900000), then I get:

```
MySQL [issue212]>  explain select c1 from t1 where c1 > 100000;
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows    | Extra                    |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
|  1 | SIMPLE      | t1    | index | i             | i    | 18      | NULL | 9700981 | Using where; Using index |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
1 row in set (11.10 sec)

MySQL [issue212]>  explain select c1 from t1 where c1 > 100000 limit 10;
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows    | Extra                    |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
|  1 | SIMPLE      | t1    | index | i             | i    | 18      | NULL | 9700981 | Using where; Using index |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
1 row in set (8.20 sec)
```

That is, if InnoDB returned precise #rows estimates, it would have gotten a bad query plan, too.

**Comment by spetrunia** [comment] 2016-03-22 11:56
Investigating the reason why InnoDB's estimates are so imprecise.
The code in `storage/innobase/btr/btr0cur.cc`,  btr_estimate_n_rows_in_range(), has this:

```
        if (slot1->nth_rec == ULINT_UNDEFINED
            || slot2->nth_rec == ULINT_UNDEFINED) {

            if (i > divergence_level + 1 && !is_n_rows_exact) {
                /* In trees whose height is > 1 our algorithm
                tends to underestimate: multiply the estimate
                by 2: */

                n_rows = n_rows * 2;
            }

            DBUG_EXECUTE_IF("bug14007649", return(n_rows););

            /* Do not estimate the number of rows in the range
            to over 1 / 2 of the estimated rows in the whole
            table */

            if (n_rows > table_n_rows / 2 && !is_n_rows_exact) {

                n_rows = table_n_rows / 2;

                /* If there are just 0 or 1 rows in the table,
                then we estimate all rows are in the range */

                if (n_rows == 0) {
                    n_rows = table_n_rows;
                }
            }
```

In the testcase for this issue, we enter with an estimate of 9,943,764, it gets multiplied by 2, then we enter the second if and the estimate is reset to be `table_n_rows / 2`

The code was added by Heikki in 2002, commit comment doesn't give any detail "btr0cur.c:
  Do not let range estimator to return over 1 / 2 of total rows in table; use longlong in range estimation"

**Comment by mdcallag** [comment] 2016-03-22 14:17
Why does that hack by Heikki matter for the case where the queries use LIMIT 10?

I get this when running a modified version of the insert benchmark to do queries concurrent with the inserts. For the example below, does it matter whether the estimate for 'rows' is 200M or 100M. In either case that is a huge full index scan compared to a 10 row range scan.

mysql> explain SELECT price,customerid FROM pi1 FORCE INDEX (marketsegment) WHERE (price>=134.54) LIMIT 10\G;
**************************\* 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: pi1
         type: index
possible_keys: marketsegment
          key: marketsegment
      key_len: 8
          ref: NULL
         rows: 197309900
        Extra: Using where; Using index
1 row in set (0.00 sec)

**Comment by mdcallag** [comment] 2016-03-22 14:19
Found using binary search, the point at which my setup switches from index to range

mysql> explain SELECT price,customerid FROM pi1 FORCE INDEX (marketsegment) WHERE (price>=154) LIMIT 10\G
**************************\* 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: pi1
         type: range
possible_keys: marketsegment
          key: marketsegment
      key_len: 4
          ref: NULL
         rows: 198264173
        Extra: Using where; Using index
1 row in set (0.00 sec)

mysql> explain SELECT price,customerid FROM pi1 FORCE INDEX (marketsegment) WHERE (price>=153) LIMIT 10\G
**************************\* 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: pi1
         type: index
possible_keys: marketsegment
          key: marketsegment
      key_len: 8
          ref: NULL
         rows: 198616700
        Extra: Using where; Using index
1 row in set (0.00 sec)

**Comment by mdcallag** [comment] 2016-03-22 14:31
Is this why I don't get a range scan?
Is "row_estimate" the estimated row count including LIMIT 10? If yes, then 2.01e8 is way off.

```
      {
        "attaching_conditions_to_tables": {
          "original_condition": "(`pi1`.`price` >= 58.42)",
          "attached_conditions_computation": [
            {
              "table": "`pi1` FORCE INDEX (`pdc`)",
              "rechecking_index_usage": {
                "recheck_reason": "low_limit",
                "limit": 10,
                "row_estimate": 2.01e8
              }
            }
          ],
          "attached_conditions_summary": [
            {
              "table": "`pi1` FORCE INDEX (`pdc`)",
              "attached": "(`pi1`.`price` >= 58.42)"
            }
          ]
        }
      },
      {
        "refine_plan": [
          {
            "table": "`pi1` FORCE INDEX (`pdc`)",
            "access_type": "index_scan"
          }
        ]
      }
```

**Comment by mdcallag** [comment] 2016-03-22 14:49
Another example where changing the constant in the WHERE clause switches the LIMIT 10 query from a range to index scan. This has optimizer trace output. In both cases, in the "rechecking_index_usage" section for "LIMIT 10"  the row_estimate value is still huge. So the only way that range gets chosen is for the cost of a huge range scan to be less than the cost of a full index scan.

 https://gist.github.com/mdcallag/b4d8fb81bd32cc437571

**Comment by spetrunia** [comment] 2016-03-22 14:54
> Is this why I don't get a range scan?

Interesting, I don't see this for either InnoDB or MyRocks on my side (while I can reproduce the issue very easily).

**Comment by mdcallag** [comment] 2016-03-22 14:57
The rechecking_index_usage output for InnoDB is similar to MyRocks --> row_estimate is huge. Does "row_estimate" in that section mean the estimate after LIMIT is applied? If yes, then it is a lousy estimate for InnoDB and MyRocks.

Here is the InnoDB output:

```
      {
        "attaching_conditions_to_tables": {
          "original_condition": "(`pi1`.`price` >= 58.42)",
          "attached_conditions_computation": [
            {
              "table": "`pi1` FORCE INDEX (`pdc`)",
              "rechecking_index_usage": {
                "recheck_reason": "low_limit",
                "limit": 10,
                "row_estimate": 4.96e7
              }
            }
          ],
          "attached_conditions_summary": [
            {
              "table": "`pi1` FORCE INDEX (`pdc`)",
              "attached": "(`pi1`.`price` >= 58.42)"
            }
          ]
        }
      },
      {
        "refine_plan": [
          {
            "table": "`pi1` FORCE INDEX (`pdc`)",
            "access_type": "range"
          }
        ]
      }
```

For this query:
SELECT price,dateandtime,customerid FROM pi1 FORCE INDEX (pdc) WHERE (price>=58.42) LIMIT 10

**Comment by mdcallag** [comment] 2016-03-22 15:11
I am using upstream 5.6.26 for InnoDB and a recent fbmysql build for MyRocks

Reproduction case is my insert benchmark - https://github.com/mdcallag/mytools/tree/master/bench/ibench

Command line for client is:
dop=1; bash np.sh 2000000000 rocksdb "" 3 /path/to/mysql/client/binary /path/to/database/data/dir $dop 10 20 0 $storage_device no 1 100 5000 1

**Comment by mdcallag** [comment] 2016-03-22 15:29
AFAIK there is no new cost information in the rechecking_index_usage section. Looking at sql_optimizer.cc the "row_estimate" is the estimate before the LIMIT is applied and no new cost information is displayed there. Allow me to be sad.

```
            Opt_trace_object trace_table(trace, "rechecking_index_usage");
            if (recheck_reason == NOT_FIRST_TABLE)
              trace_table.add_alnum("recheck_reason", "not_first_table");
            else
              trace_table.add_alnum("recheck_reason", "low_limit").
                add("limit", join->unit->select_limit_cnt).
                add("row_estimate", tab->position->records_read);
```

**Comment by mdcallag** [comment] 2016-03-22 18:26
Tried 3 variations, all choose index scan rather than range

explain SELECT price,dateandtime,customerid FROM pi1 FORCE INDEX (pdc) WHERE (price>=58.42) LIMIT 10;
explain SELECT price,dateandtime,customerid FROM pi1 FORCE INDEX (pdc) WHERE (price>=58.42) ORDER BY price LIMIT 10;
explain SELECT price,dateandtime,customerid FROM pi1 FORCE INDEX (pdc) WHERE (price>=58.42) ORDER BY price,dateandtime,customerid LIMIT 10;

```
id      select_type     table   type    possible_keys   key     key_len ref     rows    Extra
1       SIMPLE  pi1     index   pdc     pdc     14      NULL    252190800       Using where; Using index
id      select_type     table   type    possible_keys   key     key_len ref     rows    Extra
1       SIMPLE  pi1     index   pdc     pdc     14      NULL    10      Using where; Using index
id      select_type     table   type    possible_keys   key     key_len ref     rows    Extra
1       SIMPLE  pi1     index   pdc     pdc     14      NULL    10      Using where; Using index
```

index costs slightly less than range

```
                  "best_covering_index_scan": {
                    "index": "pdc",
                    "cost": 3.03e8,
                    "chosen": true
                  },
                  "setup_range_conditions": [
                  ],
                  "group_index_range": {
                    "chosen": false,
                    "cause": "not_group_by_or_distinct"
                  },
                  "analyzing_range_alternatives": {
                    "range_scan_alternatives": [
                      {
                        "index": "pdc",
                        "ranges": [
                          "58.42 < price"
                        ],
                        "index_dives_for_eq_ranges": true,
                        "rowid_ordered": false,
                        "using_mrr": false,
                        "index_only": true,
                        "rows": 268395496,
                        "cost": 3.22e8,
                        "chosen": false,
                        "cause": "cost"
                      }
                    ],
```

**Comment by mdcallag** [comment] 2016-03-22 18:59
MyISAM chooses range rather than index, but perhaps because full range has slightly lower cost than full index. Still not sure that LIMIT N optimization exists.

```
                  "best_covering_index_scan": {
                    "index": "pdc",
                    "cost": 152759,
                    "chosen": true
                  },
                  "setup_range_conditions": [
                  ],
                  "group_index_range": {
                    "chosen": false,
                    "cause": "not_group_by_or_distinct"
                  },
                  "analyzing_range_alternatives": {
                    "range_scan_alternatives": [
                      {
                        "index": "pdc",
                        "ranges": [
                          "58.42 < price"
                        ],
                        "index_dives_for_eq_ranges": true,
                        "rowid_ordered": false,
                        "using_mrr": false,
                        "index_only": true,
                        "rows": 607364,
                        "cost": 144834,
                        "chosen": true
                      }
                    ],
                    "analyzing_roworder_intersect": {
                      "usable": false,
                      "cause": "too_few_roworder_scans"
                    }
                  },
```

**Comment by yoshinorim** [comment] 2016-03-22 19:16
MyRocks estimated range scan cost was much higher than InnoDB, which made MyRocks decide to use full index scan. The cost was calculated at file->multi_range_read_info_const(), called from check_quick_select().

InnoDB supports MRR so ha_innobase::multi_range_read_info_const() returned the cost. MyRocks does not support MRR so handler::multi_range_read_info_const() returned the cost.

InnoDB cost:

```
(gdb) p *cost
$9 = {io_cost = 20585.85062240664, cpu_cost = 992190.01000000001, import_cost = 0, mem_cost = 0}
```

MyRocks cost:

```
(gdb) p *cost
$4 = {io_cost = 9938429, cpu_cost = 1987685.8100000001, import_cost = 0, mem_cost = 0}
```

Reported io_cost was 50x higher than InnoDB. It was very wrong on covering index scan. But even if estimating cost more precisely, without taking LIMIT into account, MySQL will choose full index scan.

**Comment by mdcallag** [comment] 2016-03-22 19:25
I assume we have two issues here:
1) LIMIT N optimization isn't doing much. I am not asking for this to be
fixed in MyRocks. Would be nice to file public bug.
2) Our costs for range scan are too large relative to index scan. We can
fix this (hopefully).

On Tue, Mar 22, 2016 at 12:16 PM, Yoshinori Matsunobu <
notifications@github.com> wrote:

> MyRocks estimated range scan cost was much higher than InnoDB, which made
> MyRocks decide to use full index scan. The cost was calculated at
> file->multi_range_read_info_const(), called from check_quick_select().
> 
> InnoDB supports MRR so ha_innobase::multi_range_read_info_const() returned
> the cost. MyRocks does not support MRR so
> handler::multi_range_read_info_const() returned the cost.
> 
> InnoDB cost:
> 
> (gdb) p *cost
> $9 = {io_cost = 20585.85062240664, cpu_cost = 992190.01000000001, import_cost = 0, mem_cost = 0}
> 
> MyRocks cost:
> 
> (gdb) p *cost
> $4 = {io_cost = 9938429, cpu_cost = 1987685.8100000001, import_cost = 0, mem_cost = 0}
> 
> Reported io_cost was 50x higher than InnoDB. It was very wrong on covering
> index scan. But even if estimating cost more precisely, without taking
> LIMIT into account, MySQL will choose full index scan.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/212#issuecomment-199971302

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by yoshinorim** [comment] 2016-03-22 19:49
Sergey's proposed solution (setting stats.block_size) helped to reduce estimated io_cost.

```
diff --git a/storage/rocksdb/ha_rocksdb.cc b/storage/rocksdb/ha_rocksdb.cc
index 3ccd118..6b39100 100644
--- a/storage/rocksdb/ha_rocksdb.cc
+++ b/storage/rocksdb/ha_rocksdb.cc
@@ -3774,6 +3774,9 @@ int ha_rocksdb::open(const char *name, int mode, uint test_if_locked)
   if (has_hidden_pk(table) && load_hidden_pk_value())
     DBUG_RETURN(HA_ERR_INTERNAL_ERROR);

+  /* Index block size in MyRocks: used by MySQL in query optimization */
+  stats.block_size = table_options.block_size;
+
   DBUG_RETURN(0);
 }


(gdb) p *cost
$4 = {io_cost = 46007.023148148146, cpu_cost = 1987460.4100000001, import_cost = 0, mem_cost = 0}
```

MyRocks still chose full index scan on some conditions. With some hacks like InnoDB (reducing maximum estimated rows on range scan) will fix the problem in MyRocks too though.

**Comment by yoshinorim** [comment] 2016-03-22 20:05
With records_in_range hack (setting maximum rows by range scan = total_rows/2), MyRocks always selected range scan.

```
mysql> explain select c1 from t1 where c1 > 0 limit 10;
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows    | Extra                    |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
|  1 | SIMPLE      | t1    | range | i             | i    | 9       | NULL | 5000000 | Using where; Using index |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
1 row in set (0.00 sec)

mysql> explain select c1 from t1 where c1 > 1000 limit 10;
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
| id | select_type | table | type  | possible_keys | key  | key_len | ref  | rows    | Extra                    |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
|  1 | SIMPLE      | t1    | range | i             | i    | 9       | NULL | 5000000 | Using where; Using index |
+----+-------------+-------+-------+---------------+------+---------+------+---------+--------------------------+
1 row in set (0.00 sec)
```

Estimated rows became half of the number of rows in the table t1. This was wrong, and it was side effect of the records_in_range hack. 

Here is a patch:

```
diff --git a/storage/rocksdb/ha_rocksdb.cc b/storage/rocksdb/ha_rocksdb.cc
index 3ccd118..0f562c4 100644
--- a/storage/rocksdb/ha_rocksdb.cc
+++ b/storage/rocksdb/ha_rocksdb.cc
@@ -3774,6 +3774,9 @@ int ha_rocksdb::open(const char *name, int mode, uint test_if_locked)
   if (has_hidden_pk(table) && load_hidden_pk_value())
     DBUG_RETURN(HA_ERR_INTERNAL_ERROR);

+  /* Index block size in MyRocks: used by MySQL in query optimization */
+  stats.block_size = table_options.block_size;
+
   DBUG_RETURN(0);
 }

@@ -7467,6 +7470,12 @@ ha_rows ha_rocksdb::records_in_range(uint inx, key_range *min_key,
   }

   ret = rows*sz/disk_size;
+
+  if (ret > stats.records / 2)
+  {
+    ret = stats.records / 2;
+  }
+
   if (rocksdb_debug_optimizer_n_rows > 0)
   {
     ret= rocksdb_debug_optimizer_n_rows;
```

I don't like the records_in_range() hack, but unless we find a good way to estimate LIMIT cost, probably this would be the only feasible workaround.

**Comment by yoshinorim** [comment] 2016-03-22 21:43
I noticed that when MyRocks chose full index scan, ha_rocksdb::records_in_range() returned more than maximum rows in the table, which was totally wrong.

```
explain select c1 from t1 where c1 > 3 limit 10;
br myrocks::ha_rocksdb::records_in_range
Value returned is $12 = 10037575

mysql> explain select c1 from t1 where c1 > 1000 limit 10;
Value returned is $13 = 10036300
```

We estimate the number of rows in range by GetApproximateSizes(). We need to adjust something if it was larger than stats.records, though dividing by half was not needed.

**Comment by spetrunia** [comment] 2016-03-22 21:50
@yoshinorim, yes. AFAIU actually it needs to be a little bit lower, because the cost of range scan is calculated in handler::multi_range_read_info_const()  as follows:

```
    if ((*flags & HA_MRR_INDEX_ONLY) && total_rows > 2)
      cost->add_io(index_only_read_time(keyno, total_rows) *
                   Cost_estimate::IO_BLOCK_READ_COST());
    else
      cost->add_io(read_time(keyno, n_ranges, total_rows) *
                   Cost_estimate::IO_BLOCK_READ_COST());
    cost->add_cpu(total_rows * ROW_EVALUATE_COST + 0.01);
```

Note the 0.01.  I'm not sure why it is present, but if records_in_range() returns the number of rows that's equal to #rows in the table, then range scan will be still a bit more expensive than the full index scan.

Capping #rows at #rows_in_table *0.99 should be sufficient, it seems

**Comment by spetrunia** [comment] 2016-03-22 22:31
@mdcallag wrote:

> Still not sure that LIMIT N optimization exists.

I debugged what happens in 

```
  "rechecking_index_usage": {
    "recheck_reason": "low_limit"
```

section when no ORDER BY clause is present. 

The code around "rechecking_index_usage" was developed with intent to do optimization for ORDER BY .. LIMIT. When ORDER BY is not present, it concludes that no index provides the "required ordering", and so it doesn't attempt to do any LIMIT-aware optimization.

When ORDER BY clause is present, the optimizer in some cases does make a choice that takes $n from `LIMIT $n` into account.  The code that makes that choice shows up as  `reconsidering_access_paths_for_index_ordering` in the optimizer_trace. However, a lot of details about the choice are not printed (e.g. how many rows the optimizer expects to scan before reaching LIMIT rows, the cost of this partial scan, etc)

**Comment by yoshinorim** [comment] 2016-03-22 23:30
Filed a diff based on discussions so far -- https://reviews.facebook.net/D55869 . This doesn't solve LIMIT, but would give as good optimizer plans as MyISAM.

**Comment by mdcallag** [comment] 2016-03-23 00:13
Filed a feature request to get LIMIT N support in the cost-based optimizer

**Closed as completed** 2016-03-23 16:20 UTC
Labels: bug, myrocks, high-pri
