### ISSUE TITLE
Insert with CARTESIAN JOIN  - 'std::bad_alloc'  what():  std::bad_alloc

### ISSUE THREAD

**Issue by Komport** [facebook/mysql-5.6#449] opened 2016-11-22 18:07 UTC
Hi Dear All.
Today during test I have faced  below issue. You can find all details below.

OS - VERSION="16.04.1 LTS (Xenial Xerus)"
free-m command output.
              total        used        free      shared  buff/cache   available
Mem:            990          58         397           6         533         887
Swap:             0           0           0

mysql> use rsyslogdb;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A
Database changed
mysql> select count(*) from SystemEvents;
+----------+
| count(*) |
+----------+
|     3811 |
+----------+
1 row in set (0.09 sec)

mysql> select count(*) from SystemEvents_copy;
+----------+
| count(*) |
+----------+
|     3811 |
+----------+
1 row in set (0.09 sec)
mysql> insert into SystemEventsT select a.* from SystemEvents a,SystemEvents_copy b;
ERROR 2013 (HY000): Lost connection to MySQL server during query
mysql> 161122 17:32:04 mysqld_safe Number of processes running now: 0
161122 17:32:04 mysqld_safe mysqld restarted

[bt.txt](https://github.com/facebook/mysql-5.6/files/607145/bt.txt)
[bt_full.txt](https://github.com/facebook/mysql-5.6/files/607146/bt_full.txt)
[mysqld.txt](https://github.com/facebook/mysql-5.6/files/607150/mysqld.txt)
[mycnf.txt](https://github.com/facebook/mysql-5.6/files/607176/mycnf.txt)
[table_structure.txt](https://github.com/facebook/mysql-5.6/files/607177/table_structure.txt)

**Comment by mdcallag** [comment] 2016-11-22 18:30
std::bad_alloc means out-of-memory. Will try to reproduce on my build

**Comment by mdcallag** [comment] 2016-11-22 19:10
Duplicate of https://github.com/facebook/mysql-5.6/issues/365. MyRocks buffers all uncommitted changes before commit. In this case that is about 4000 x 4000 rows. The peak memory consumption occurs during commit and the peak is either 2X or 3X the memory required to buffer the changes. This peak is transient as changes are copied into the memtable.

The workaround for large transactions is described at https://github.com/facebook/mysql-5.6/issues/365#issuecomment-257038461

**Closed as completed by mdcallag** 2016-11-22 19:10 UTC
Labels: bug, duplicate, myrocks
