### ISSUE TITLE
7% regression in linkbench load performance from May7 to Jul5

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#279] opened 2016-07-11 19:50 UTC
Linkbench load with 2 connections on the same hardware and almost same my.cnf is about 7% slower for a build from July 5 using MySQL githash 7806cc compared to a May 7 build using githash 2406e9. Normalized CPU (CPU seconds / insert) has increased by about 10% in the July 5 build. Sync-on-commit is disabled for the WAL and the binlog.

The database is cached. Perf degrades with binlog enabled and disabled.

Next are flat and hierarchical CPU profiles. I will share the hierarchical profiles directly as they are too big to paste but look interesting.

May7

```
     7.51%  my-oneconnectio  mysqld               [.] MYSQLparse
     6.60%  my-oneconnectio  libc-2.20.so         [.] __memcmp_sse4_1
     6.50%  my-oneconnectio  mysqld               [.] lex_one_token
     5.73%  my-oneconnectio  mysqld               [.] Item_hex_string::hex_string_init
     4.79%  my-oneconnectio  mysqld               [.] rocksdb::WriteBatchEntryComparator::operator()
     2.11%  my-oneconnectio  mysqld               [.] myrocks::Rdb_pk_comparator::Compare
     1.75%  my-oneconnectio  mysqld               [.] rocksdb::InternalKeyComparator::Compare
     1.62%  my-oneconnectio  mysqld               [.] rocksdb::MemTable::KeyComparator::operator()
     1.59%  my-oneconnectio  mysqld               [.] rocksdb::MemTable::Get
     1.55%  my-oneconnectio  mysqld               [.] rocksdb::TransactionImpl::TryLock
     1.52%  my-oneconnectio  mysqld               [.] rocksdb::MemTable::Add
     1.45%  my-oneconnectio  libc-2.20.so         [.] __memcpy_avx_unaligned
     1.37%  my-oneconnectio  mysqld               [.] std::_Hashtable<std::string, std::pair<std::string const, rocksdb::TransactionKeyMapInfo>, std::allocator<std::pair<std::string const, rocksdb::TransactionKeyMapInfo> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find
     1.18%  my-oneconnectio  mysqld               [.] rocksdb::StatisticsImpl::recordTick
     1.17%  my-oneconnectio  mysqld               [.] rocksdb::TransactionLockMgr::UnLock
     1.14%  my-oneconnectio  mysqld               [.] rocksdb::WriteBatchWithIndex::Rep::UpdateExistingEntryWithCfId
     1.00%  my-oneconnectio  mysqld               [.] rocksdb::SkipList<rocksdb::WriteBatchIndexEntry*, rocksdb::WriteBatchEntryComparator const&>::Insert
     0.99%  my-oneconnectio  mysqld               [.] myrocks::Rdb_rev_comparator::Compare
     0.99%  my-oneconnectio  mysqld               [.] rocksdb::HistogramStat::Add
     0.99%  my-oneconnectio  mysqld               [.] rocksdb::InlineSkipList<rocksdb::MemTableRep::KeyComparator const&>::Insert
```

July5 shows memcmp with 1.25X more CPU

```
     8.77%  my-oneconnectio  libc-2.20.so         [.] __memcmp_sse4_1
     6.75%  my-oneconnectio  mysqld.yo            [.] MYSQLparse
     6.22%  my-oneconnectio  mysqld.yo            [.] lex_one_token
     5.46%  my-oneconnectio  mysqld.yo            [.] Item_hex_string::hex_string_init
     4.23%  my-oneconnectio  mysqld.yo            [.] rocksdb::WriteBatchEntryComparator::operator()
     3.94%  my-oneconnectio  mysqld.yo            [.] rocksdb::InternalKeyComparator::Compare
     3.29%  my-oneconnectio  mysqld.yo            [.] rocksdb::MemTable::KeyComparator::operator()
     3.13%  my-oneconnectio  mysqld.yo            [.] myrocks::Rdb_pk_comparator::Compare
     1.99%  my-oneconnectio  mysqld.yo            [.] rocksdb::BlockIter::BinarySeek
     1.53%  my-oneconnectio  mysqld.yo            [.] rocksdb::(anonymous namespace)::SkipListRep::Get
     1.41%  my-oneconnectio  libc-2.20.so         [.] __memcpy_avx_unaligned
     1.37%  my-oneconnectio  mysqld.yo            [.] rocksdb::TransactionImpl::TryLock
     1.13%  my-oneconnectio  mysqld.yo            [.] std::_Hashtable<std::string, std::pair<std::string const, rocksdb::TransactionKeyMapInfo>, std::allocator<std::pair<std::string const, rocksdb::TransactionKeyMapInfo> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find
     1.01%  my-oneconnectio  mysqld.yo            [.] rocksdb::TransactionBaseImpl::TrackKey
     0.97%  my-oneconnectio  mysqld.yo            [.] rocksdb::BlockIter::Seek
     0.97%  my-oneconnectio  mysqld.yo            [.] rocksdb::TransactionLockMgr::UnLock
     0.97%  my-oneconnectio  mysqld.yo            [.] rocksdb::WriteBatchWithIndex::Rep::UpdateExistingEntryWithCfId
     0.94%  my-oneconnectio  mysqld.yo            [.] rocksdb::WBWIIteratorImpl::SeekToLast
     0.88%  my-oneconnectio  mysqld.yo            [.] myrocks::Rdb_rev_comparator::Compare
     0.88%  my-oneconnectio  mysqld.yo            [.] rocksdb::HistogramStat::Add
     0.81%  my-oneconnectio  mysqld.yo            [.] rocksdb::Version::Get
```

**Comment by mdcallag** [comment] 2016-07-12 18:15
Why is rocksdb_block_cache_data_hit about 2X larger for Jul5 -- ~25M vs ~12M? This means there were twice the accesses for data blocks in Jul5. That looks like a big regression.
https://gist.github.com/mdcallag/9b7c2d9069a322af977725fe18223d61

There is nothing to show the number of calls to get and scan data from RocksDB. That would be useful here. Something like rocksdb_get_\* and the equivalent for range scans. As it is I have to guess at the source of data block accesses.

**Comment by mdcallag** [comment] 2016-07-12 18:18
Sample insert statements:

```
INSERT INTO linkdb.linktable(id1, id2, link_type, visibility, data, time, version) VALUES (3792162, 3792465, 123456790, 1, x'585e', 1464237989769, 0),(3792162, 3792466, 123456790, 1, x'343b48335e',   ...  , (3792419, 3792419, 123456789, 1, x'502533', 1466170573571, 0) ON DUPLICATE KEY UPDATE visibility = VALUES(visibility)
```

**Comment by hermanlee** [comment] 2016-07-12 18:36
Just to verify, what are the table schemas? Are they using binary collation? There are some diffs checked in to add support for varchar index lookups with non-binary collations, but they're not fully enabled until Sergey's diff is checked in. If the schema is using binary collation, then the potentially problems from the varchar index lookups shouldn't apply.

@lth

**Comment by spetrunia** [comment] 2016-07-12 18:44
unless there has been some very recent change in linkbench schema:  the only indexed varchar column is:

```
CREATE TABLE `linktable` (
...      
  `data` varchar(255) NOT NULL DEFAULT '',
...
  KEY `id1_type` (`id1`,`link_type`,`visibility`,`time`,`id2`,`version`,`data`)
) ENGINE=RocksDB DEFAULT CHARSET=latin1 collate latin1_bin;
```

so it's latin1_bin, which supported index-only since long ago. 

#257 will change end-space handling for latin1_bin, but this doesn't seem to have anything to do with the bug.

**Comment by yoshinorim** [comment] 2016-07-14 21:44
Root cause was prefix bloom filter config has changed from 20 to 12, which reduced bloom filter useful rate. I updated our wiki so that linktable should continue to use 20 -- https://github.com/facebook/mysql-5.6/wiki/my.cnf-tuning

**Closed as completed by yoshinorim** 2016-07-14 21:44 UTC
Labels: bug, myrocks
