### ISSUE TITLE
Assertion "error <= 193" failed

### ISSUE THREAD

**Issue by tplavcic** [facebook/mysql-5.6#316] opened 2016-09-15 13:40 UTC
This can be seen only when using MyRocks and it doesn't reproduce with InnoDB on the same binary.

InnoDB:

```
mysql> DROP DATABASE test;CREATE DATABASE test;USE test;
Query OK, 0 rows affected (0.00 sec)

Query OK, 1 row affected (0.01 sec)

Database changed
mysql> CREATE TABLE t4(a int);
Query OK, 0 rows affected (0.24 sec)

mysql> INSERT INTO t4 VALUES(1);
Query OK, 1 row affected (0.03 sec)

mysql> SET SQL_MODE=TRADITIONAL;
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO t4 SELECT a + 2 FROM t4 LIMIT ROWS EXAMINED 6;
ERROR 1892 (HY000): Query execution was interrupted. The query examined at least 7 rows, which exceeds LIMIT ROWS EXAMINED (6). The query result may be incomplete.
```

MyRocks:

```
mysql> DROP DATABASE test;CREATE DATABASE test;USE test;
Query OK, 0 rows affected (0.00 sec)

Query OK, 1 row affected (0.00 sec)

Database changed
mysql> CREATE TABLE t4(a int);
Query OK, 0 rows affected (0.07 sec)

mysql> INSERT INTO t4 VALUES(1);
Query OK, 1 row affected (0.00 sec)

mysql> SET SQL_MODE=TRADITIONAL;
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO t4 SELECT a + 2 FROM t4 LIMIT ROWS EXAMINED 6;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

Error log:

```
mysqld: /home/tomislav.plavcic/workdir/FB-mysql-5.6/storage/rocksdb/ha_rocksdb.cc:4572: virtual bool myrocks::ha_rocksdb::get_error_message(int, String*): Assertion `error <= 193' failed.
13:30:10 UTC - mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed, 
something is definitely wrong and this may fail.

key_buffer_size=8388608
read_buffer_size=131072
max_used_connections=1
max_threads=151
thread_count=1
connection_count=1
It is possible that mysqld could use up to 
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 68968 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x7f1e301c2000
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 7f1e34e2bb50 thread_stack 0x50000
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(my_print_stacktrace+0x35)[0xf270e0]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(handle_fatal_signal+0x39f)[0xb982d7]
/lib64/libpthread.so.0(+0xf100)[0x7f1e34836100]
/lib64/libc.so.6(gsignal+0x37)[0x7f1e325b25f7]
/lib64/libc.so.6(abort+0x148)[0x7f1e325b3ce8]
/lib64/libc.so.6(+0x2e566)[0x7f1e325ab566]
/lib64/libc.so.6(+0x2e612)[0x7f1e325ab612]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(myrocks::ha_rocksdb::get_error_message(int, String*)+0x54)[0x1271404]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(handler::print_error(int, int)+0x80d)[0xa94c79]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(select_insert::send_eof()+0x3f8)[0xc2e7f6]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld[0xc18bbf]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(JOIN::exec()+0x71f)[0xc168d1]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld[0xc7b55b]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(mysql_select(THD*, TABLE_LIST*, unsigned int, List<Item>&, Item*, SQL_I_List<st_order>*, SQL_I_List<st_order>*, Item*, unsigned long long, select_result*, st_select_lex_unit*, st_select_lex*)+0x239)[0xc7b835]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(handle_select(THD*, select_result*, unsigned long)+0x20e)[0xc79930]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(mysql_execute_command(THD*, unsigned long long*, unsigned long long*)+0x375c)[0xc4a1fd]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(mysql_parse(THD*, char*, unsigned int, Parser_state*, unsigned long long*, char*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char*)+0x62c)[0xc52b71]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(dispatch_command(enum_server_command, THD*, char*, unsigned int)+0x11fd)[0xc43c04]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(do_command(THD*)+0x311)[0xc4218c]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(do_handle_one_connection(THD*)+0x26a)[0xc084f4]
/home/tomislav.plavcic/workdir/fb-mysql-5.6.27-linux-x86_64-7525065/bin/mysqld(handle_one_connection+0x20)[0xc07cd0]
/lib64/libpthread.so.0(+0x7dc5)[0x7f1e3482edc5]
/lib64/libc.so.6(clone+0x6d)[0x7f1e32673ced]

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Last run query buffer: INSERT INTO t4 SELECT a + 2 FROM t4 LIMIT ROWS EXAMINED 6
Query (7f1e20c31010): INSERT INTO t4 SELECT a + 2 FROM t4 LIMIT ROWS EXAMINED 6
Connection ID (thread ID): 1
Status: KILL_BAD_DATA
```

**Comment by gunnarku** [comment] 2016-09-15 19:23
Duplicate of https://github.com/facebook/mysql-5.6/issues/313

**Closed as completed by gunnarku** 2016-09-15 19:23 UTC
Labels: bug, myrocks
