### ISSUE TITLE
rocksdb.type_varchar is unstable

### ISSUE THREAD

**Issue by george-lorch** [facebook/mysql-5.6#612] opened 2017-04-21 15:33 UTC
```
rocksdb.type_varchar                     w2 [ fail ]
        Test ended at 2017-04-20 22:34:17

CURRENT_TEST: rocksdb.type_varchar
--- /mnt/workspace/fb-mysql-5.6/mysql-test/suite/rocksdb/r/type_varchar.result	2017-04-21 05:11:02.355689669 +0300
+++ /mnt/workspace/fb-mysql-5.6/Debug/mysql-test/var/2/log/type_varchar.reject	2017-04-21 05:34:16.916514364 +0300
@@ -653,13 +653,13 @@
 explain
 select col1, hex(col1) from t1 where col1 < 'b';
 id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
-1	SIMPLE	t1	#	col1	col1	259	NULL	#	Using where
+1	SIMPLE	t1	#	col1	NULL	NULL	NULL	#	Using where
 select col1, hex(col1) from t1 where col1 < 'b';
 col1	hex(col1)
-a  		0061002000200009
+ab	00610062
 a 	00610020
 a	0061
-ab	00610062
+a  		0061002000200009
 delete from t1;
 insert into t1 values(10, '', 'empty');
 insert into t1 values(11, repeat(' ', 8), '8x-space');
```

Problem is within type_varchar_endspace.inc

Before calling EXPLAIN SELECT ..., explicit ANALYZE TABLE should be run. EXPLAIN SELECTs and SELECTs on col1 should explicitly use ORDER BY col1

**Comment by hermanlee** [comment] 2017-04-21 17:09
Thanks George! I've been seeing some instability here and haven't tracked down the cause of the differences in optimizer stats for the query plan to be different. Is the analyze table solution sufficient?

**Comment by george-lorch** [comment] 2017-04-21 17:14
It seems to have solved the issue in our Percona Server tree. This test failed regularly enough for me to feel confident the ANALYSE was enough to stabilize the test. We also had similar problems w/ TokuDB being quite non-deterministic when it came to row counts, cardinality stats, etc and applied a similar fix there.

**Comment by hermanlee** [comment] 2017-04-21 17:16
Thanks! I'll apply that change to the test to see if it stabilizes on our side as well.

**Comment by hermanlee** [comment] 2017-04-24 16:51
I pushed a change that adds analyze table to the test. I haven't seen it in testing over the weekend, so will close this task. Feel free to re-open if the problem continues.

**Closed as completed by hermanlee** 2017-04-24 16:51 UTC
