### ISSUE TITLE
MyRocks may return "Can't find record" which is unexpected

### ISSUE THREAD

**Issue by hustchensi** [facebook/mysql-5.6#1026] opened 2019-06-04 08:33 UTC
How to reproduce:

test table definition:

```sql
CREATE TABLE `extra` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `a` varchar(36) NOT NULL ,
  `b` varchar(128) NOT NULL ,
  `c` varchar(10240) NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_idx` (`a`,`b`),
) ENGINE=ROCKSDB
```

run several threads concurrently, each run the following logic loops for several times:

```sql
start transaction;
insert into extra(a,b,c) values (?,'file_type','498081') on duplicate key update c=values(c);
commit;
```

The value of field `a` is shared by the threads, and generated like:

``` go
func inc() {
        for {
                atomic.AddUint64(&a_val, 1)
                time.Sleep(10 * time.Millisecond)
        }
}
```

dive into the code, the above sql will call the handlers in the following turn:
- first insert ha_rocksdb::update_row -> update_write_row -> check_uniqueness_and_lock
- after duplicate error, ha_rocksdb::index_read_map -> index_read_map_impl

**the problem is:**
- TrxA, in check_uniqueness_and_lock, PK (index number 0) is checked first, since it's auto increment, **get_for_update** will success always, and **SetSnapshotOnNextOperation** will be called, the snapshot is saved,  assumed it's **SN is 10**;
- then TrxB commit, and write the same uniq index row, assumed the commit **SN is 11**;
- TrxA continue to  check the  uniq key (index number 1) in check_and_lock_sk,  and **get_for_update success**, since TrxB is committed; and read_key_exact will found the key is duplicated (since the iterator using the current data, of cource SN 11 can be read), so index_read_map_impl is called by the sql layer in **write_record** in sql_insert.cc
- finally, ** index_read_map_impl** read using snapshot at **SN 10**, TrxB will be unvisiable,  the sql result will be **Can't find record**

**the reason**:
- in TrxA ** SetSnapshotOnNextOperation** is called by the first **get_for_update** in the above description, and the snapshot of transaction is set at the corresponding SN;
- But TrxB maybe committed between the two get_for_update;
- TrxA can see TrxB when check duplicate because it does not use the snapshot of transaction;
```c
ha_rocksdb::check_and_lock_sk
 rocksdb::Iterator *const iter = row_info.tx->get_iterator(
      kd.get_cf(), total_order_seek, fill_cache, lower_bound_slice,
      upper_bound_slice, true /* read current data */,
      false /* acquire snapshot */);
```
- TrxA cannot see TrxB when get the duplicate row because it use the snapshot of transaction;
```c
index_read_map_impl -> setup_scan_iterator
     m_scan_it = tx->get_iterator(kd.get_cf(), skip_bloom, fill_cache,
                                   m_scan_it_lower_bound_slice,
                                   m_scan_it_upper_bound_slice);
```

**Comment by hermanlee** [comment] 2019-06-07 17:50
Thanks for filing the issue with a great test case.

**Comment by hermanlee** [comment] 2019-06-10 17:03
@lth and I looked at this. For the case where the full SK key (including primary key parts) is known, we may be able to fix this by issue a get_for_update() for the secondary key instead of using the iterator to scan the secondary key. The get_for_update() would automatically use the latest snapshot. If we don't have the full key at this point, then rely on the existing iterator scheme. We still need to verify if the extended key parts are passed down correctly to this codepath (or do what we did for insert..update, cache the row which has the full key, and use the cached row to generate the primary key).

**Comment by spetrunia** [comment] 2019-06-11 22:19
Some thoughts:

There are two approaches to ensuring transactional isolation one can use:

Approach#1 : Snapshot Checking
- Read rows through the transaction's snapshot.
- When we are reading a row that we intend to modify, we get a lock on it, and then do snapshot checking  on it (check that there were no changes since our snapshot was created)

Approach #2: Read-Committed (this is what InnoDB does)
- a DML statement will get locks on rows that it intends to modify, and then will read and operate on the latest committed data.

The cause of this bug is that MyRocks uses approach #1 for the most part, but uses #2 to prevent unique secondary key violations.

If we wanted to use #1 always, the check for unique secondary key would be like:
```cpp
Get a lock on the secondary_key_value; // This is what we currently do
// do "snapshot checking":
get an iterator to search for the secondary_key_value; //ignore the snapshot
if (we find a row that was modified after our snapshot was taken)
  report Snapshot violation error; 
```

This way, instead of "Can't find record", the second transaction would get "Snapshot violation" error. This is a valid behavior (any application that uses transaction should be prepared to re-try).

**Comment by spetrunia** [comment] 2019-06-17 20:21
A testcase:
Patch the server:

``` diff
diff --git a/storage/rocksdb/ha_rocksdb.cc b/storage/rocksdb/ha_rocksdb.cc
index cb7e24b162f..d8dcfea1bb8 100644
--- a/storage/rocksdb/ha_rocksdb.cc
+++ b/storage/rocksdb/ha_rocksdb.cc
@@ -9280,6 +9280,7 @@ int ha_rocksdb::check_uniqueness_and_lock(
         rc = HA_EXIT_SUCCESS;
       } else {
         rc = check_and_lock_unique_pk(key_id, row_info, &found);
+        DEBUG_SYNC(ha_thd(), "rocksdb.after_unique_pk_check");
       }
     } else {
       rc = check_and_lock_sk(key_id, row_info, &found);
```

Then run this MTR test case:


``` sql
--source include/have_rocksdb.inc
--source include/have_debug_sync.inc

connect (con1, localhost, root,,);
connection default;

--disable_warnings
set debug_sync='RESET';
--enable_warnings

CREATE TABLE `extra` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `a` varchar(36) NOT NULL ,
  `b` varchar(128) NOT NULL ,
  `c` varchar(10240) NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_idx` (`a`,`b`)
) ENGINE=ROCKSDB;

insert into extra values (1,1,1,1), (2,2,2,2);

## TRX A:
begin;
set debug_sync='rocksdb.after_unique_pk_check SIGNAL trx_a_sleep WAIT_FOR trx_a_cont';
send
insert into extra(a,b,c) values (10,'file_type','trx-a') on duplicate key update c=values(c);

connection con1;
# TRX B:
set debug_sync='now WAIT_FOR trx_a_sleep';
begin;
insert into extra(a,b,c) values (10,'file_type','trx-b') on duplicate key update c=values(c);
commit;
set debug_sync='now SIGNAL trx_a_cont';


connection default;
reap;

disconnect con1;
rollback;
drop table extra;
```
The output would be:
```
CURRENT_TEST: rocksdb.bug1026
mysqltest: At line 40: query 'reap' failed: 1032: Can't find record in 'extra'
```

**Comment by spetrunia** [comment] 2019-06-17 20:24
Proposed fix (correct, but I'm not sure if it is performant):

``` diff
diff --git a/storage/rocksdb/ha_rocksdb.cc b/storage/rocksdb/ha_rocksdb.cc
index cb7e24b162f..816e1b64662 100644
--- a/storage/rocksdb/ha_rocksdb.cc
+++ b/storage/rocksdb/ha_rocksdb.cc
@@ -9247,6 +9247,16 @@ int ha_rocksdb::check_and_lock_sk(const uint key_id,
   iter->Seek(new_slice);
   *found = !read_key_exact(kd, iter, all_parts_used, new_slice,
                            row_info.tx->m_snapshot_timestamp);
+  // psergey: if found, try to lock it so that snapshot checking is done.
+  if (*found) {
+    rocksdb::Slice found_key= iter->key();
+    const rocksdb::Status s =
+        get_for_update(row_info.tx, kd.get_cf(), found_key, nullptr);
+    if (!s.ok() && !s.IsNotFound()) {
+      return row_info.tx->set_status_error(table->in_use, s, kd, m_tbl_def,
+                                           m_table_handler);
+    }
+  }
   delete iter;
 
   return HA_EXIT_SUCCESS;
```

This will make the above testcase fail with: 
```
CURRENT_TEST: rocksdb.bug1026
mysqltest: At line 40: query 'reap' failed: 1213: Deadlock found when trying to get lock; try restarting transaction (snapshot conflict)
```

**Comment by spetrunia** [comment] 2019-06-17 20:30
The idea is as follows: MyRocks uses Snapshot Checking (lock the rowkey; then check it has
not been modified since our snapshot was taken).
This breaks down for unique secondary keys, because we lock the secondary key (not extended by PK), but the rows that are modified on disk are the {secondary_key, pk} tuples.

This way, get_for_update(secondary_key, nullptr) doesn't perform snapshot checking (because this rowkey doesn't exist in the database, it's used only for locking).

So, if the iterator reads a duplicate row, let's perform snapshot checking on it: call `get_for_update(..., found_key, nullptr)`. Note that the last parameter being nullptr, it will just do locking + snapshot checking. No data reads will be done.

**Comment by lth** [comment] 2019-06-19 23:01
@spetrunia I think what we discussed earlier in @hermanlee's comment was that, instead of reading the key via `iter->Seek` and then "rereading" the key via `get_for_update`, do you think it's possible just construct the exact key upfront and call `get_for_update` without the iterator? For repeatable read, get_for_update will return snapshot conflict, and for read committed, we'd just lock and read the latest row.

So with your proposed fix, we have:
```
get_for_update(on unique key without pk extension)
iter->Seek(...)
get_for_update(on found key)
```

But I wonder if we can just do:
```
get_for_update(on unique key without pk extension)
get_for_update(on unique key with pk extension)
```

I think this will be better for performance (because point lookups are generally cheaper). It looks like we should be passed the whole record (so that we have pk parts) when ha_write_row/ha_update_row is called.

Edit: Actually, I guess we rely on this part to do duplicate key checking, and we do not necessarily know the pk parts for the existing duplicate key (if one exists). We probably can't get around using an iterator then.

**Comment by yizhang82** [comment] 2019-06-21 17:56
@lth @spetrunia Longer term we should just support gap locks and do locking reads like innodb, then we wouldn't have this problem and simply get snapshot violation later.
@spetrunia Given that you already proposed the fix + test (and we agree it's the right fix to go with), would you mind submit a PR?

**Comment by royguo** [comment] 2019-07-24 10:40
@yizhang82 If MyRocks was configured as `Read Committed`, shouldn't we let transaction A override transaction B's result? since the original sql was `insert on duplicate ... update ...`.

Accordding to @spetrunia 's fix, looks like trx A just bypass the uniqueness checking and let the insertion success (New to myrocks, please correct me if I am wrong, thanks a lot!).

**Comment by spetrunia** [comment] 2020-04-20 20:29
Pull request: https://github.com/facebook/mysql-5.6/pull/1125

**Closed as completed** 2020-07-07 20:54 UTC
