### ISSUE TITLE
Odd hang/option interaction with --rocksdb-rate-limiter-bytes-per-sec and --rocksdb-db-write-buffer-size

### ISSUE THREAD

**Issue by RoelVdP** [facebook/mysql-5.6#216] opened 2016-03-23 03:06 UTC
During testing, a hang was seen. On debugging found this;

Default options: --no-defaults --default-tmp-storage-engine=MyISAM --rocksdb --skip-innodb --default-storage-engine=RocksDB 

Add this to the above: --rocksdb-rate-limiter-bytes-per-sec=2 --rocksdb-db-write-buffer-size=1. Result:

```
mysql> CREATE TABLE t1 (id INT);
Query OK, 0 rows affected (0.07 sec)

mysql> CREATE TABLE t2 (id INT);
<client will hang, perhaps somewhat to be expected looking at the options given>
```

The server will also not shutdown properly when using mysqladmin shutdown.

Add this instead (and clean data dir first): --rocksdb-rate-limiter-bytes-per-sec=2. Result:

```
mysql> CREATE TABLE t1 (id INT);
Query OK, 0 rows affected (0.06 sec)

mysql> CREATE TABLE t2 (id INT);
Query OK, 0 rows affected (0.04 sec)
```

Yet, server will not shutdown properly when using mysqladmin shutdown.

Add this instead (and clean data dir first): --rocksdb-db-write-buffer-size=1. Result:

```
mysql> CREATE TABLE t1 (id INT);
Query OK, 0 rows affected (0.07 sec)

mysql> CREATE TABLE t2 (id INT);
Query OK, 0 rows affected (0.11 sec)
```

Plus the server will shutdown quickly when using mysqladmin shutdown.

There seems to be some things here which do not look correct.

**Comment by yoshinorim** [comment] 2016-03-23 03:20
--rocksdb-rate-limiter-bytes-per-sec=2 and --rocksdb-db-write-buffer-size=1 are too small. I think we can restrict minimum positive integer values for some variables.

**Comment by RoelVdP** [comment] 2016-03-23 03:22
Yes, it would be good to set reasonable limits for all rocksdb options. One thing though is that the interaction shown above seems odd?

**Comment by jkedgar** [comment] 2016-04-12 20:59
I'll look into the odd behavior.

Yoshinori, what minimum values would you you like me to add for rocksdb-rate-limiter-bytes-per-sec and rocksdb-db-write-buffer-size?

**Comment by jkedgar** [comment] 2016-04-12 22:27
It turns out that the whole problem is caused by setting the rocksdb-rate-limiter-bytes-per-sec to such a low value.  Internally in RocksDB there was a calculation done to convert this value into bytes-per-period where the size of the period was configurable (the default was 100ms).  This calculation did not check for the value becoming 0, which is what happened in this case.  With a value of 0 bytes per period nothing was ever getting written, which was why the server froze on shutdown.

In the first case you mentioned, when the client froze, I'm guessing that the second option you provided must have forced the server to do a compaction or other operation that required writing during the second CREATE TABLE and so the server never responded to the client (as it was waiting for writing that wasn't occurring) causing the client to hang.  Once I fixed the issue where the bytes per period became 0, this behavior reverted to normal behavior.

I have a diff out on RocksDB to provide a minimum amount for the bytes per period value (Igor on the RocksDB suggested 100) at https://reviews.facebook.net/D56631.

**Comment by jkedgar** [comment] 2016-04-13 16:15
The diff got accepted and is now landed, but it won't be pulled into MyRocks automatically.  On the assumption that this isn't a critical issue I'm going to just let it get pulled in next time someone updates the rocksdb submodule, but if it is needed earlier, let me know and I can pull it in directly.

**Comment by jkedgar** [comment] 2016-04-13 16:15
Also - I don't think there is any need to add minimums in MyRocks for these values after this fix.

**Closed as completed by jkedgar** 2016-04-13 16:15 UTC

**Comment by jkedgar** [comment] 2016-04-14 16:28
Another change has caused the change in the rocksdb submodule to updated, so now the current MyRocks code has this fix.

**Comment by RoelVdP** [comment] 2016-04-18 18:01
:+1:
